(function(){
'use strict';
var KEY='iam-career-hub-state-v9';
var data=window.ROADMAP||{career:{target:'IAM Analyst / IAM Engineer'},phases:[]};
var learning=window.LEARNING||{};var resources=window.RESOURCES||{};var certs=window.CERTIFICATIONS||{};var app=document.getElementById('app');
function allTasks(){var a=[];(data.phases||[]).forEach(function(p){(p.tasks||[]).forEach(function(t){a.push({id:t.id,name:t.name,type:t.type||'knowledge',mins:t.mins||60,pre:t.pre||[],phaseId:p.id,phase:p.name,goal:p.goal||''});});});return a;}
function getTask(id){var a=allTasks();for(var i=0;i<a.length;i++)if(a[i].id===id)return a[i];return null;}
function stages(t){if(t.type==='lab')return ['Estudar','Executar','Troubleshoot','Evidenciar'];if(t.type==='validate')return ['Resolver cenário','Explicar sem consulta','Registrar validação'];return ['Estudar','Praticar','Recapitular','Validar'];}
function fresh(){return {stageDone:{},done:{},evidence:{},english:{minutes:0,sessions:0},history:[],started:new Date().toISOString()};}
var state;try{state=JSON.parse(localStorage.getItem(KEY)||'null')||fresh();}catch(e){state=fresh();}
if(!state.stageDone)state.stageDone={};if(!state.done)state.done={};if(!state.evidence)state.evidence={};if(!state.english)state.english={minutes:0,sessions:0};if(!state.history)state.history=[];
function done(id){return !!state.done[id];}function ready(t){for(var i=0;i<t.pre.length;i++)if(!done(t.pre[i]))return false;return true;}function completeStage(id,i){return !!(state.stageDone[id]&&state.stageDone[id][i]);}
function pct(a,b){return b?Math.round(a*100/b):0;}function taskPct(t){var a=state.stageDone[t.id]||[],n=0,s=stages(t);for(var i=0;i<s.length;i++)if(a[i])n++;return pct(n,s.length);}function overall(){var a=allTasks(),n=0;for(var i=0;i<a.length;i++)if(done(a[i].id))n++;return pct(n,a.length);}
function nextTask(){var a=allTasks();for(var i=0;i<a.length;i++)if(!done(a[i].id)&&ready(a[i]))return a[i];return null;}
function esc(s){s=String(s==null?'':s);return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function bar(v){return '<div class="bar"><i style="width:'+v+'%"></i></div>';}
function nav(){var n=[['today','Today'],['roadmap','Roadmap'],['progress','Progress'],['certs','Certificações'],['labs','Labs'],['settings','Config']];var h='<nav>';for(var i=0;i<n.length;i++)h+='<button class="nav-btn" data-view="'+n[i][0]+'">'+n[i][1]+'</button>';return h+'</nav>';}
function shell(content){app.innerHTML='<div class="app-shell"><aside class="sidebar"><div class="brand"><strong>IAM</strong><span>CAREER HUB</span></div><div class="career-chip"><span>Objetivo</span><b>'+esc(data.career.target)+'</b><small>Cloud IAM</small></div>'+nav()+'<div class="sidebar-foot"><span>2h estudo</span><span>1h inglês</span></div></aside><main>'+content+'</main></div>';}
function header(k,title,sub){return '<header class="top"><div><div class="eyebrow">'+esc(k)+'</div><h1>'+esc(title)+'</h1>'+(sub?'<p>'+esc(sub)+'</p>':'')+'</div><time>'+new Date().toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'})+'</time></header>';}
function taskRow(t){return '<div class="task '+(done(t.id)?'done':'')+'"><div><b>'+(done(t.id)?'✓ ':'')+esc(t.name)+'</b><small>'+t.mins+' min · '+(done(t.id)?'concluído':ready(t)?taskPct(t)+'% validado':'bloqueado')+'</small></div><div class="task-actions"><button class="icon-btn" data-page-task="'+esc(t.id)+'">Abrir</button></div></div>';}
function renderToday(){var t=nextTask(),after=[],a=allTasks();for(var i=0;i<a.length&&after.length<5;i++)if(!done(a[i].id)&&ready(a[i])&&(!t||a[i].id!==t.id))after.push(a[i]);var focus=t?'<div class="focus-label">'+esc(t.phase)+'</div><h2>'+esc(t.name)+'</h2><div class="focus-meta">'+t.mins+' min · '+taskPct(t)+'% validado</div>'+bar(taskPct(t))+'<div class="focus-actions"><button class="primary" data-page-task="'+esc(t.id)+'">Continuar →</button><span>'+overall()+'% da carreira</span></div>':'<h2>Trilha concluída</h2>';var list='';after.forEach(function(x){list+=taskRow(x);});shell(header('TODAY',t?'Seu próximo passo':'Trilha concluída',t?'A competência abre em uma página própria, com todo o conteúdo e as etapas.':'Nenhuma competência pendente.')+'<section class="today-focus">'+focus+'</section><section class="today-grid"><div class="panel"><div class="panel-head"><div><h3>Depois disso</h3><small>já desbloqueado</small></div></div>'+list+'<div class="empty">'+(after.length?'':'Conclua o passo atual para liberar o próximo.')+'</div></div><div class="panel"><div class="panel-head"><div><h3>Progresso</h3><small>competências</small></div></div><div class="big-number">'+overall()+'%</div>'+bar(overall())+'<div class="mini-stats"><span>Inglês <b>'+state.english.minutes+' min</b></span></div></div></section>');}
function renderRoadmap(){var h='';(data.phases||[]).forEach(function(p){var d=0;p.tasks.forEach(function(t){if(done(t.id))d++;});var active=nextTask(),open=active&&active.phaseId===p.id;h+='<details class="phase-card" '+(open?'open':'')+'><summary><div><b>'+esc(p.id)+' · '+esc(p.name)+'</b><small>'+d+'/'+p.tasks.length+'</small></div><strong>'+pct(d,p.tasks.length)+'%</strong></summary>'+bar(pct(d,p.tasks.length))+'<div class="phase-tasks">';p.tasks.forEach(function(t){h+=taskRow(t);});h+='</div></details>';});shell(header('ROADMAP','Seu caminho','Abra uma competência em página própria para estudar, praticar e validar.')+'<section class="roadmap-list">'+h+'</section>');}
function renderProgress(){var a=allTasks(),domains='';(data.phases||[]).forEach(function(p){var d=0;p.tasks.forEach(function(t){if(done(t.id))d++;});domains+='<div class="domain"><div><span>'+esc(p.name)+'</span><b>'+pct(d,p.tasks.length)+'%</b></div>'+bar(pct(d,p.tasks.length))+'</div>';});shell(header('PROGRESS','Seu progresso','Calculado automaticamente pelas competências validadas.')+'<section class="progress-hero"><div class="big-number">'+overall()+'%</div>'+bar(overall())+'<span>'+a.filter(function(t){return done(t.id);}).length+' de '+a.length+'</span></section><section class="domain-list">'+domains+'</section><section class="panel english-panel"><div><h3>Inglês técnico</h3><p>'+state.english.sessions+' sessões · '+state.english.minutes+' minutos</p></div><button class="primary" id="english60">+ 60 min</button></section>');}
function certLevel(c){if(c.level==='Fundamental'||c.level==='Foundational')return 'Básico';if(c.level==='Associate'||c.level==='Professional')return 'Intermediário';return 'Avançado';}
function certBadge(c){var s=c.status||'';return s==='primary'?'PRINCIPAL':s.indexOf('optional')>=0?'OPCIONAL':s.indexOf('specialization')>=0?'ESPECIALIZAÇÃO':s==='advanced'||s==='long-term'?'AVANÇADO':'RECOMENDADO';}
function certCard(c){var n=0,total=(c.gate||[]).length;for(var i=0;i<(c.gate||[]).length;i++)if(done(c.gate[i]))n++;var progress=total?pct(n,total):0;return '<article class="cert-card"><div class="cert-card-head"><div><span class="cert-level">'+certLevel(c)+'</span><h3>'+esc(c.name)+'</h3><small>'+esc(c.provider)+' · '+esc(c.level)+'</small></div><span class="cert-status '+(c.priority==='critical'?'critical':'')+'">'+certBadge(c)+'</span></div><p>'+esc(c.why)+'</p>'+bar(progress)+'<div class="cert-foot"><span>Pré-requisitos de competência: '+n+'/'+total+'</span><b>'+progress+'%</b></div></article>';}
function renderCerts(){var all=certs.tracks||[];var levels=[['Básico','Fundamentos para entrar na trilha'],['Intermediário','Certificações que constroem o núcleo IAM/Cloud'],['Avançado','Arquitetura, segurança e especialização'],['Especialização / Opcional','Só faça quando a função-alvo justificar']];var h='<section class="cert-path panel"><div class="eyebrow">SEQUÊNCIA PRINCIPAL</div><h2>Como seguir</h2><p>Não faça todas. A sequência abaixo prioriza retorno profissional e acompanha o seu objetivo IAM/Cloud.</p><div class="cert-sequence"><div><b>01</b><span>SC-900</span></div><i>→</i><div><b>02</b><span>AZ-900</span></div><i>→</i><div class="main-step"><b>03</b><span>SC-300</span><small>principal</small></div><i>→</i><div><b>04</b><span>AZ-104</span><small>conforme vaga</small></div><i>→</i><div><b>05</b><span>AWS SAA</span></div><i>→</i><div><b>06</b><span>AWS Security</span></div><i>→</i><div><b>07</b><span>SC-100</span></div></div></section>';
levels.forEach(function(group){var list=all.filter(function(c){return certLevel(c)===group[0]|| (group[0]==='Especialização / Opcional' && (c.status==='optional'||c.status==='specialization-later'));});if(!list.length)return;h+='<section class="cert-section"><div class="cert-section-head"><div><h2>'+group[0]+'</h2><p>'+group[1]+'</p></div></div><div class="cert-grid">';list.forEach(function(c){h+=certCard(c);});h+='</div></section>';});
shell(header('CERTIFICAÇÕES','Trilha de certificações','Separadas por nível, prioridade e momento correto. Certificação não substitui laboratório.')+h);}
function renderLabs(){shell(header('LABS','Laboratórios','Evidências práticas são solicitadas quando a competência chega ao Today.')+'<section class="content-grid"><div class="panel"><h3>Existentes</h3><div class="evidence"><b>Cloud Security</b><span>Azure · Entra ID · RBAC · VNet · NSG · VM</span></div><div class="evidence"><b>On-Premises</b><span>AD · DNS · DHCP · GPO · WSUS · Wazuh · Suricata</span></div></div><div class="panel"><h3>Próximos</h3>'+['Hybrid Identity','Enterprise SSO','PIM + Governance','Graph Automation','Entra → AWS Federation','IAM Architecture'].map(function(x){return '<div class="evidence"><b>'+x+'</b><small>liberado automaticamente</small></div>';}).join('')+'</div></section>');}
function renderSettings(){shell(header('CONFIG','Configurações','Dados e rotina.')+'<section class="panel settings"><div class="setting"><span>Objetivo</span><b>'+esc(data.career.target)+'</b></div><div class="setting"><span>Rotina</span><b>2h estudo + 1h inglês</b></div><div class="actions"><button class="secondary" id="export">Exportar</button><button class="secondary" id="import">Importar</button><button class="danger" id="reset">Resetar</button><input id="file" type="file" accept="application/json" hidden></div></section>');}
function getResources(t){if(resources.find)return resources.find(t);return [];}function detailData(t){return learning.enrich?learning.enrich(t):{goal:'Dominar a competência.',study:['Estudar documentação oficial.'],practice:['Executar a prática.'],validate:['Explicar sem consulta.'],evidence:'Registrar evidência.'};}
function renderTaskPage(id){var t=getTask(id);if(!t){render('today');return;}var l=detailData(t),rs=getResources(t),st=stages(t),html='<div class="task-page"><div class="back-row"><button class="secondary" id="backTask">← Voltar</button><span>'+esc(t.phase)+'</span></div><div class="task-page-head"><div class="eyebrow">COMPETÊNCIA '+esc(t.id)+'</div><h1>'+esc(t.name)+'</h1><p>'+t.mins+' min · '+(ready(t)?'disponível':'bloqueada')+' · '+taskPct(t)+'% validado</p>'+bar(taskPct(t))+'</div><div class="task-page-grid"><article class="panel learning-panel"><section><h2>O que dominar</h2><p>'+esc(l.goal)+'</p></section><section><h2>Estudar</h2>';l.study.forEach(function(x){html+='<p class="detail-line">'+esc(x)+'</p>';});html+='</section><section><h2>Praticar</h2>';l.practice.forEach(function(x){html+='<p class="detail-line">'+esc(x)+'</p>';});html+='</section><section><h2>Validar</h2>';l.validate.forEach(function(x){html+='<p class="detail-line">'+esc(x)+'</p>';});html+='</section><section><h2>Evidência esperada</h2><p>'+esc(l.evidence)+'</p></section>';if(rs.length){html+='<section><h2>Material oficial</h2>';rs.forEach(function(r){html+='<p class="detail-line"><a href="'+esc(r.url)+'" target="_blank" rel="noopener">'+esc(r.name)+'</a></p>';});html+='</section>';}html+='</article><aside class="task-page-side"><div class="panel"><h2>Etapas</h2><div class="page-stages">';st.forEach(function(s,i){var locked=i>0&&!completeStage(t.id,i-1);html+='<button class="stage '+(completeStage(t.id,i)?'complete':'')+'" data-stage-page="'+esc(t.id)+'" data-index="'+i+'" '+(!ready(t)&&!done(t.id)||locked?'disabled':'')+'><b>'+(completeStage(t.id,i)?'✓ ':'')+esc(s)+'</b><small>Etapa '+(i+1)+(locked?' · bloqueada':'')+'</small></button>';});html+='</div><p class="muted">Só avance quando conseguir demonstrar a etapa.</p></div><div class="panel evidence-panel"><label class="evidence-input"><span>Evidência / nota desta competência</span><textarea id="evidenceText" rows="7" placeholder="Registre o que você executou, resultado, comando, configuração ou link para evidência.">'+esc(state.evidence[t.id]||'')+'</textarea><button class="secondary" id="saveEvidence">Salvar evidência</button></label></div></aside></div></div>';shell(html);bindTaskPage(t.id);}
function toggleStage(id,i){var t=getTask(id);if(!t||(!ready(t)&&!done(id)))return;var prev=i>0&&completeStage(id,i-1);if(i>0&&!prev)return;var a=state.stageDone[id]||[];a[i]=!a[i];if(!a[i]){for(var z=i+1;z<stages(t).length;z++)a[z]=false;delete state.done[id];}state.stageDone[id]=a;var ok=true;for(var j=0;j<stages(t).length;j++)if(!a[j])ok=false;if(ok&&!done(id)){var at=new Date().toISOString();state.done[id]={at:at,evidence:state.evidence[id]||''};state.history.push({id:id,at:at});}localStorage.setItem(KEY,JSON.stringify(state));renderTaskPage(id);}
function bindTaskPage(id){var b=document.getElementById('backTask');if(b)b.onclick=function(){location.hash='';render('today');};document.querySelectorAll('[data-stage-page]').forEach(function(x){x.onclick=function(){toggleStage(x.getAttribute('data-stage-page'),Number(x.getAttribute('data-index')));};});var s=document.getElementById('saveEvidence');if(s)s.onclick=function(){state.evidence[id]=document.getElementById('evidenceText').value;localStorage.setItem(KEY,JSON.stringify(state));renderTaskPage(id);};}
function bind(){document.querySelectorAll('[data-view]').forEach(function(x){x.onclick=function(){location.hash='';localStorage.setItem('iam-view',x.getAttribute('data-view'));render(x.getAttribute('data-view'));};});document.querySelectorAll('[data-page-task]').forEach(function(x){x.onclick=function(){location.hash='task/'+encodeURIComponent(x.getAttribute('data-page-task'));renderTaskPage(x.getAttribute('data-page-task'));};});var e=document.getElementById('english60');if(e)e.onclick=function(){state.english.minutes+=60;state.english.sessions++;localStorage.setItem(KEY,JSON.stringify(state));render('progress');};var r=document.getElementById('reset');if(r)r.onclick=function(){if(confirm('Resetar todo o progresso?')){state=fresh();localStorage.setItem(KEY,JSON.stringify(state));render('today');}};var ex=document.getElementById('export');if(ex)ex.onclick=function(){var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='iam-career-progress.json';a.click();};var im=document.getElementById('import');if(im)im.onclick=function(){document.getElementById('file').click();};var f=document.getElementById('file');if(f)f.onchange=function(){var reader=new FileReader();reader.onload=function(){try{state=JSON.parse(reader.result);localStorage.setItem(KEY,JSON.stringify(state));render('today');}catch(err){alert('Arquivo inválido.');}};reader.readAsText(f.files[0]);};}
function render(v){var hash=location.hash.replace(/^#/,'');if(hash.indexOf('task/')===0){renderTaskPage(decodeURIComponent(hash.slice(5)));return;}if(v==='roadmap')renderRoadmap();else if(v==='progress')renderProgress();else if(v==='certs')renderCerts();else if(v==='labs')renderLabs();else if(v==='settings')renderSettings();else renderToday();bind();var navs=document.querySelectorAll('[data-view]');navs.forEach(function(n){if(n.getAttribute('data-view')===v)n.classList.add('active');});}
window.addEventListener('hashchange',function(){var h=location.hash.replace(/^#/,'');if(h.indexOf('task/')===0)renderTaskPage(decodeURIComponent(h.slice(5)));else render(localStorage.getItem('iam-view')||'today');});
render(localStorage.getItem('iam-view')||'today');
})();
