(function(){
'use strict';
var KEY='iam-career-hub-state-v7';
var data=window.ROADMAP||{career:{target:'IAM Analyst / IAM Engineer'},phases:[]};
var learning=window.LEARNING||{};
var resources=window.RESOURCES||{};
var app=document.getElementById('app');
function allTasks(){var a=[];var ps=data.phases||[];for(var i=0;i<ps.length;i++){var ts=ps[i].tasks||[];for(var j=0;j<ts.length;j++){var t=ts[j];a.push({id:t.id,name:t.name,type:t.type||'knowledge',mins:t.mins||60,pre:t.pre||[],phaseId:ps[i].id,phase:ps[i].name,goal:ps[i].goal||''});}}return a;}
function getTask(id){var a=allTasks();for(var i=0;i<a.length;i++){if(a[i].id===id)return a[i];}return null;}
function stages(t){if(t.type==='lab')return ['Estudar','Executar','Troubleshoot','Evidenciar'];if(t.type==='validate')return ['Resolver cenário','Explicar sem consulta','Registrar validação'];return ['Estudar','Praticar','Recapitular','Validar'];}
function fresh(){return {stageDone:{},done:{},english:{minutes:0,sessions:0},history:[],started:new Date().toISOString()};}
var state;
try{state=JSON.parse(localStorage.getItem(KEY)||'null')||fresh();}catch(e){state=fresh();}
if(!state.stageDone)state.stageDone={};if(!state.done)state.done={};if(!state.english)state.english={minutes:0,sessions:0};if(!state.history)state.history=[];
function done(id){return !!state.done[id];}
function ready(t){for(var i=0;i<t.pre.length;i++){if(!done(t.pre[i]))return false;}return true;}
function completeStage(id,i){return !!(state.stageDone[id]&&state.stageDone[id][i]);}
function pct(a,b){return b?Math.round(a*100/b):0;}
function taskPct(t){var a=state.stageDone[t.id]||[],n=0,s=stages(t);for(var i=0;i<s.length;i++){if(a[i])n++;}return pct(n,s.length);}
function overall(){var a=allTasks(),n=0;for(var i=0;i<a.length;i++){if(done(a[i].id))n++;}return pct(n,a.length);}
function nextTask(){var a=allTasks();for(var i=0;i<a.length;i++){if(!done(a[i].id)&&ready(a[i]))return a[i];}return null;}
function esc(s){s=String(s==null?'':s);return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function bar(v){return '<div class="bar"><i style="width:'+v+'%"></i></div>';}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render(view());}
function view(){return localStorage.getItem('iam-view')||'today';}
function nav(){var n=[['today','Today'],['roadmap','Roadmap'],['progress','Progress'],['certs','Certificações'],['labs','Labs'],['settings','Config']];var h='<nav>';for(var i=0;i<n.length;i++)h+='<button class="nav-btn" data-view="'+n[i][0]+'">'+n[i][1]+'</button>';return h+'</nav>';}
function header(k,title,sub){return '<header class="top"><div><div class="eyebrow">'+esc(k)+'</div><h1>'+esc(title)+'</h1>'+(sub?'<p>'+esc(sub)+'</p>':'')+'</div><time>'+new Date().toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'})+'</time></header>';}
function shell(content){app.innerHTML='<div class="app-shell"><aside class="sidebar"><div class="brand"><strong>IAM</strong><span>CAREER HUB</span></div><div class="career-chip"><span>Objetivo</span><b>'+esc(data.career.target)+'</b><small>Cloud IAM</small></div>'+nav()+'<div class="sidebar-foot"><span>2h estudo</span><span>1h inglês</span></div></aside><main>'+content+'</main></div><div id="modal" class="modal hidden"><div class="modal-card" id="modalBody"></div></div>';}
function taskRow(t){return '<div class="task '+(done(t.id)?'done':'')+'"><div><b>'+(done(t.id)?'✓ ':'')+esc(t.name)+'</b><small>'+t.mins+' min · '+(done(t.id)?'concluído':ready(t)?taskPct(t)+'% validado':'bloqueado')+'</small></div><button class="icon-btn" data-open="'+esc(t.id)+'">Abrir</button></div>';}
function renderToday(){var t=nextTask();var after=[];var a=allTasks();for(var i=0;i<a.length&&after.length<5;i++){if(!done(a[i].id)&&ready(a[i])&&(!t||a[i].id!==t.id))after.push(a[i]);}var focus=t?'<div class="focus-label">'+esc(t.phase)+'</div><h2>'+esc(t.name)+'</h2><div class="focus-meta">'+t.mins+' min · '+taskPct(t)+'% validado</div>'+bar(taskPct(t))+'<div class="focus-actions"><button class="primary" data-open="'+esc(t.id)+'">Continuar →</button><span>'+overall()+'% da carreira</span></div>':'<h2>Trilha concluída</h2>';var list='';for(var j=0;j<after.length;j++)list+=taskRow(after[j]);shell(header('TODAY',t?'Seu próximo passo':'Trilha concluída',t?'Faça apenas o que aparece aqui.':'Nenhuma competência pendente.')+'<section class="today-focus">'+focus+'</section><section class="today-grid"><div class="panel"><div class="panel-head"><div><h3>Depois disso</h3><small>já desbloqueado</small></div></div>'+list+'<div class="empty">'+(after.length?'':'Conclua o passo atual para liberar o próximo.')+'</div></div><div class="panel"><div class="panel-head"><div><h3>Progresso</h3><small>competências</small></div></div><div class="big-number">'+overall()+'%</div>'+bar(overall())+'<div class="mini-stats"><span>Inglês <b>'+state.english.minutes+' min</b></span></div></div></section>');}
function renderRoadmap(){var h='';var ps=data.phases||[];for(var i=0;i<ps.length;i++){var p=ps[i],d=0;for(var j=0;j<p.tasks.length;j++)if(done(p.tasks[j].id))d++;var active=nextTask(),open=active&&active.phaseId===p.id;h+='<details class="phase-card" '+(open?'open':'')+'><summary><div><b>'+esc(p.id)+' · '+esc(p.name)+'</b><small>'+d+'/'+p.tasks.length+'</small></div><strong>'+pct(d,p.tasks.length)+'%</strong></summary>'+bar(pct(d,p.tasks.length))+'<div class="phase-tasks">';for(var k=0;k<p.tasks.length;k++)h+=taskRow(p.tasks[k]);h+='</div></details>';}shell(header('ROADMAP','Seu caminho','Abra uma competência para estudar, praticar e validar.')+'<section class="roadmap-list">'+h+'</section>');}
function renderProgress(){var a=allTasks(),domains='';for(var i=0;i<(data.phases||[]).length;i++){var p=data.phases[i],d=0;for(var j=0;j<p.tasks.length;j++)if(done(p.tasks[j].id))d++;domains+='<div class="domain"><div><span>'+esc(p.name)+'</span><b>'+pct(d,p.tasks.length)+'%</b></div>'+bar(pct(d,p.tasks.length))+'</div>';}shell(header('PROGRESS','Seu progresso','Calculado automaticamente pelas competências validadas.')+'<section class="progress-hero"><div class="big-number">'+overall()+'%</div>'+bar(overall())+'<span>'+a.filter(function(t){return done(t.id);}).length+' de '+a.length+'</span></section><section class="domain-list">'+domains+'</section><section class="panel english-panel"><div><h3>Inglês técnico</h3><p>'+state.english.sessions+' sessões · '+state.english.minutes+' minutos</p></div><button class="primary" id="english60">+ 60 min</button></section>');}
function renderCerts(){var groups=[['SC-900',['F01-01','F01-07']],['SC-300',['F03-01','F03-04','F03-06','F06-02']],['AZ-900',['F01-07','F07-01']],['AWS Cloud Practitioner',['F09-01','F09-02']]];var h='';for(var i=0;i<groups.length;i++){var g=groups[i],n=0,ts=[];for(var j=0;j<g[1].length;j++){var t=getTask(g[1][j]);if(t){ts.push(t);if(done(t.id))n++;}}h+='<article class="cert-card"><div class="cert-top"><span>'+esc(g[0])+'</span><b>'+pct(n,ts.length)+'%</b></div>'+bar(pct(n,ts.length));for(var k=0;k<ts.length;k++)h+=taskRow(ts[k]);h+='</article>';}shell(header('CERTIFICAÇÕES','Certificações','Acompanham a formação, sem substituir domínio prático.')+'<section class="cert-grid">'+h+'</section>');}
function renderLabs(){shell(header('LABS','Laboratórios','Evidências práticas são solicitadas quando a competência chega ao Today.')+'<section class="content-grid"><div class="panel"><h3>Existentes</h3><div class="evidence"><b>Cloud Security</b><span>Azure · Entra ID · RBAC · VNet · NSG · VM</span></div><div class="evidence"><b>On-Premises</b><span>AD · DNS · DHCP · GPO · WSUS · Wazuh · Suricata</span></div></div><div class="panel"><h3>Próximos</h3>'+['Hybrid Identity','Enterprise SSO','PIM + Governance','Graph Automation','Entra → AWS Federation','IAM Architecture'].map(function(x){return '<div class="evidence"><b>'+x+'</b><small>liberado automaticamente</small></div>';}).join('')+'</div></section>');}
function renderSettings(){shell(header('CONFIG','Configurações','Dados e rotina.')+'<section class="panel settings"><div class="setting"><span>Objetivo</span><b>'+esc(data.career.target)+'</b></div><div class="setting"><span>Rotina</span><b>2h estudo + 1h inglês</b></div><div class="actions"><button class="secondary" id="export">Exportar</button><button class="secondary" id="import">Importar</button><button class="danger" id="reset">Resetar</button><input id="file" type="file" accept="application/json" hidden></div></section>');}
function getResources(t){var list=resources.official||[];var n=t.name.toLowerCase();var out=[];for(var i=0;i<list.length;i++){var tags=list[i].tags||[];var ok=false;for(var j=0;j<tags.length;j++)if(n.indexOf(String(tags[j]).toLowerCase())>=0)ok=true;if(ok)out.push(list[i]);if(out.length===4)break;}return out;}
function taskDetail(id){var t=getTask(id);if(!t)return;var l=learning.enrich?learning.enrich(t):{goal:'Dominar a competência.',study:['Estudar documentação oficial.'],practice:['Executar a prática.'],validate:['Explicar sem consulta.'],evidence:'Registrar evidência.'};var rs=getResources(t),st=stages(t),body=document.getElementById('modalBody'),modal=document.getElementById('modal');modal.classList.remove('hidden');var html='<button class="close" data-close>×</button><div class="eyebrow">'+esc(t.phase)+'</div><h2>'+esc(t.name)+'</h2><p class="muted">'+t.mins+' min · '+(ready(t)?'disponível':'bloqueado')+' · '+taskPct(t)+'%</p>'+bar(taskPct(t))+'<div class="learning"><section><h3>O que dominar</h3><p>'+esc(l.goal)+'</p></section><section><h3>Estudar</h3>';for(var i=0;i<l.study.length;i++)html+='<p>• '+esc(l.study[i])+'</p>';html+='</section><section><h3>Praticar</h3>';for(i=0;i<l.practice.length;i++)html+='<p>• '+esc(l.practice[i])+'</p>';html+='</section><section><h3>Validar</h3>';for(i=0;i<l.validate.length;i++)html+='<p>• '+esc(l.validate[i])+'</p>';html+='</section><section><h3>Evidência</h3><p>'+esc(l.evidence)+'</p></section>';if(rs.length){html+='<section><h3>Material oficial</h3>';for(i=0;i<rs.length;i++)html+='<p>• <a href="'+esc(rs[i].url)+'" target="_blank" rel="noopener">'+esc(rs[i].name)+'</a></p>';html+='</section>';}html+='</div><div class="stage-list">';for(i=0;i<st.length;i++)html+='<button class="stage '+(completeStage(t.id,i)?'complete':'')+'" data-stage="'+esc(t.id)+'" data-index="'+i+'" '+(!ready(t)&&!done(t.id)?'disabled':'')+'><b>'+(completeStage(t.id,i)?'✓ ':'')+esc(st[i])+'</b><small>Etapa '+(i+1)+'</small></button>';html+='</div><p class="muted">Só conclua uma etapa quando conseguir demonstrá-la.</p>';body.innerHTML=html;bindModal();}
function toggleStage(id,i){var t=getTask(id);if(!t||(!ready(t)&&!done(id)))return;var a=state.stageDone[id]||[];a[i]=!a[i];state.stageDone[id]=a;var st=stages(t),ok=true;for(var j=0;j<st.length;j++)if(!a[j])ok=false;if(ok&&!done(id)){var at=new Date().toISOString();state.done[id]={at:at};state.history.push({id:id,at:at});}if(!ok)delete state.done[id];save();}
function bindModal(){var c=document.querySelector('[data-close]');if(c)c.onclick=function(){document.getElementById('modal').classList.add('hidden');};document.querySelectorAll('[data-stage]').forEach(function(x){x.onclick=function(){toggleStage(x.getAttribute('data-stage'),Number(x.getAttribute('data-index')));};});}
function bind(){document.querySelectorAll('[data-view]').forEach(function(x){x.onclick=function(){render(x.getAttribute('data-view'));};});document.querySelectorAll('[data-open]').forEach(function(x){x.onclick=function(){taskDetail(x.getAttribute('data-open'));};});bindModal();var e=document.getElementById('english60');if(e)e.onclick=function(){state.english.minutes+=60;state.english.sessions++;save();};var r=document.getElementById('reset');if(r)r.onclick=function(){if(confirm('Resetar todo o progresso?')){state=fresh();save();}};var ex=document.getElementById('export');if(ex)ex.onclick=function(){var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='iam-career-progress.json';a.click();};var im=document.getElementById('import');if(im)im.onclick=function(){document.getElementById('file').click();};var f=document.getElementById('file');if(f)f.onchange=function(){var reader=new FileReader();reader.onload=function(){try{state=JSON.parse(reader.result);save();}catch(err){alert('Arquivo inválido');}};reader.readAsText(f.files[0]);};}
function render(v){localStorage.setItem('iam-view',v);if(v==='roadmap')renderRoadmap();else if(v==='progress')renderProgress();else if(v==='certs')renderCerts();else if(v==='labs')renderLabs();else if(v==='settings')renderSettings();else renderToday();bind();}
render(view());
})();