(function(){
'use strict';
var KEY='iam-career-hub-state-v6';
var data=window.ROADMAP;
var learning=window.LEARNING;
var resourceCatalog=window.RESOURCES;
var app=document.getElementById('app');

function tasks(){
  var out=[];
  data.phases.forEach(function(p){p.tasks.forEach(function(t){out.push({id:t.id,name:t.name,type:t.type,mins:t.mins,pre:t.pre||[],phaseId:p.id,phase:p.name,goal:p.goal});});});
  return out;
}
function task(id){var a=tasks();for(var i=0;i<a.length;i++)if(a[i].id===id)return a[i];return null;}
function phase(id){for(var i=0;i<data.phases.length;i++)if(data.phases[i].id===id)return data.phases[i];return null;}
function stages(t){if(t.type==='lab')return ['Estudar','Executar','Troubleshoot','Evidenciar'];if(t.type==='validate')return ['Resolver cenário','Explicar sem consulta','Registrar validação'];return ['Estudar','Praticar','Recapitular','Validar'];}
function fresh(){return {stageDone:{},done:{},english:{minutes:0,sessions:0},history:[],started:new Date().toISOString()};}
var state;
try{state=JSON.parse(localStorage.getItem(KEY)||'null')||fresh();}catch(e){state=fresh();}
if(!state.stageDone)state.stageDone={};if(!state.done)state.done={};if(!state.english)state.english={minutes:0,sessions:0};if(!state.history)state.history=[];
function isDone(id){return !!state.done[id];}
function ready(t){for(var i=0;i<t.pre.length;i++)if(!isDone(t.pre[i]))return false;return true;}
function stageComplete(id,i){return !!(state.stageDone[id]&&state.stageDone[id][i]);}
function percent(a,b){return b?Math.round(a/b*100):0;}
function taskPercent(t){var a=state.stageDone[t.id]||[],n=0;for(var i=0;i<a.length;i++)if(a[i])n++;return percent(n,stages(t).length);}
function completed(){return tasks().filter(function(t){return isDone(t.id);});}
function overall(){return percent(completed().length,tasks().length);}
function nextTask(){var a=tasks();for(var i=0;i<a.length;i++)if(!isDone(a[i].id)&&ready(a[i]))return a[i];return null;}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function bar(v){return '<div class="bar"><i style="width:'+v+'%"></i></div>';}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render(currentView());}
function currentView(){return localStorage.getItem('iam-view')||'today';}
function header(k,t,s){return '<header class="top"><div><div class="eyebrow">'+k+'</div><h1>'+esc(t)+'</h1>'+(s?'<p>'+esc(s)+'</p>':'')+'</div><time>'+new Date().toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'})+'</time></header>';}
function nav(){return '<nav>'+[['today','Today'],['roadmap','Roadmap'],['progress','Progress'],['certs','Certificações'],['labs','Labs'],['settings','Config']].map(function(x){return '<button class="nav-btn" data-view="'+x[0]+'">'+x[1]+'</button>';}).join('')+'</nav>';}
function shell(content){app.innerHTML='<div class="app-shell"><aside class="sidebar"><div class="brand"><strong>IAM</strong><span>CAREER HUB</span></div><div class="career-chip"><span>Objetivo</span><b>'+esc(data.career.target)+'</b><small>Cloud IAM</small></div>'+nav()+'<div class="sidebar-foot"><span>2h estudo</span><span>1h inglês</span></div></aside><main>'+content+'</main></div><div id="modal" class="modal hidden"><div class="modal-card" id="modalBody"></div></div>';}
function taskRow(t){return '<div class="task '+(isDone(t.id)?'done':'')+'"><div><b>'+(isDone(t.id)?'✓ ':'')+esc(t.name)+'</b><small>'+t.mins+' min · '+(isDone(t.id)?'concluído':ready(t)?taskPercent(t)+'% validado':'bloqueado')+'</small></div><button class="icon-btn" data-open="'+t.id+'">Abrir</button></div>';}
function renderToday(){var t=nextTask(),p=t?phase(t.phaseId):null;var all=tasks(),up=[];for(var i=0;i<all.length&&up.length<5;i++)if(!isDone(all[i].id)&&ready(all[i]))up.push(all[i]);var tm=0;var today=new Date().toDateString();state.history.forEach(function(h){if(new Date(h.at).toDateString()===today){var x=task(h.id);if(x)tm+=x.mins;}});shell(header('TODAY',t?'Seu próximo passo':'Trilha concluída',t?'Faça apenas o que aparece aqui.':'Nenhuma competência desbloqueada pendente.')+'<section class="today-focus">'+(t?'<div class="focus-label">'+esc(p.name)+'</div><h2>'+esc(t.name)+'</h2><div class="focus-meta">'+t.mins+' min · '+taskPercent(t)+'% validado</div>'+bar(taskPercent(t))+'<div class="focus-actions"><button class="primary" data-open="'+t.id+'">Continuar →</button><span>'+overall()+'% da carreira</span></div>':'<h2>Você chegou ao fim da trilha atual.</h2>')+'</section><section class="today-grid"><div class="panel"><div class="panel-head"><div><h3>Depois disso</h3><small>já desbloqueado</small></div></div>'+up.filter(function(x){return !t||x.id!==t.id;}).map(taskRow).join('')+'<div class="empty">'+(up.length?'':'Conclua o passo atual para liberar o próximo.')+'</div></div><div class="panel"><div class="panel-head"><div><h3>Progresso</h3><small>'+completed().length+' de '+all.length+'</small></div></div><div class="big-number">'+overall()+'%</div>'+bar(overall())+'<div class="mini-stats"><span>Hoje <b>'+tm+' min</b></span><span>Inglês <b>'+state.english.minutes+' min</b></span></div></div></section>');}
function renderRoadmap(){shell(header('ROADMAP','Seu caminho','Detalhes aparecem somente quando você abre uma competência.')+'<section class="roadmap-list">'+data.phases.map(function(p){var d=p.tasks.filter(function(t){return isDone(t.id);}).length,v=percent(d,p.tasks.length),n=nextTask();var active=n&&p.tasks.some(function(t){return t.id===n.id;});return '<details class="phase-card" '+(active?'open':'')+'><summary><div><b>'+esc(p.id)+' · '+esc(p.name)+'</b><small>'+d+'/'+p.tasks.length+'</small></div><strong>'+v+'%</strong></summary>'+bar(v)+'<div class="phase-tasks">'+p.tasks.map(taskRow).join('')+'</div></details>';}).join('')+'</section>');}
function renderProgress(){shell(header('PROGRESS','Seu progresso','Calculado automaticamente pelas competências validadas.')+'<section class="progress-hero"><div class="big-number">'+overall()+'%</div>'+bar(overall())+'<span>'+completed().length+' de '+tasks().length+'</span></section><section class="domain-list">'+data.phases.map(function(p){var d=p.tasks.filter(function(t){return isDone(t.id);}).length,v=percent(d,p.tasks.length);return '<div class="domain"><div><span>'+esc(p.name)+'</span><b>'+v+'%</b></div>'+bar(v)+'</div>';}).join('')+'</section><section class="panel english-panel"><div><h3>Inglês técnico</h3><p>'+state.english.sessions+' sessões · '+state.english.minutes+' minutos</p></div><button class="primary" id="english60">+ 60 min</button></section>');}
function renderCerts(){var groups=[['SC-900',['F01-01','F01-07']],['SC-300',['F03-01','F03-04','F03-06','F06-02']],['AZ-900',['F01-07','F07-01']],['AWS Cloud Practitioner',['F09-01','F09-02']]];shell(header('CERTIFICAÇÕES','Certificações','Acompanham a formação, não substituem domínio prático.')+'<section class="cert-grid">'+groups.map(function(g){var ts=g[1].map(task).filter(Boolean),d=ts.filter(function(t){return isDone(t.id);}).length,v=percent(d,ts.length);return '<article class="cert-card"><div class="cert-top"><span>'+esc(g[0])+'</span><b>'+v+'%</b></div>'+bar(v)+ts.map(taskRow).join('')+'</article>';}).join('')+'</section>');}
function renderLabs(){shell(header('LABS','Laboratórios','Evidências serão revalidadas quando a competência chegar ao Today.')+'<section class="content-grid"><div class="panel"><h3>Existentes</h3><div class="evidence"><b>Cloud Security</b><span>Azure · Entra ID · RBAC · VNet · NSG · VM</span></div><div class="evidence"><b>On-Premises</b><span>AD · DNS · DHCP · GPO · WSUS · Wazuh · Suricata</span></div></div><div class="panel"><h3>Próximos</h3>'+['Hybrid Identity','Enterprise SSO','PIM + Governance','Graph Automation','Entra → AWS Federation','IAM Architecture'].map(function(x){return '<div class="evidence"><b>'+x+'</b><small>liberado automaticamente</small></div>';}).join('')+'</div></section>');}
function renderSettings(){shell(header('CONFIG','Configurações','Somente controles de dados e rotina.')+'<section class="panel settings"><div class="setting"><span>Objetivo</span><b>'+esc(data.career.target)+'</b></div><div class="setting"><span>Rotina</span><b>2h estudo + 1h inglês</b></div><div class="actions"><button class="secondary" id="export">Exportar</button><button class="secondary" id="import">Importar</button><button class="danger" id="reset">Resetar</button><input id="file" type="file" accept="application/json" hidden></div></section>');}
function getResources(t){if(!resourceCatalog||!resourceCatalog.official)return [];var n=t.name.toLowerCase();return resourceCatalog.official.filter(function(r){return r.tags.some(function(tag){return n.indexOf(tag.toLowerCase())>=0;});}).slice(0,4);}
function taskDetail(id){var t=task(id);if(!t)return;var l=learning&&learning.enrich?learning.enrich(t):{goal:'Dominar a competência.',study:['Estudar documentação oficial.'],practice:['Executar prática.'],validate:['Explicar sem consulta.'],evidence:'Registrar evidência.'};var rs=getResources(t),st=stages(t);var modal=document.getElementById('modal');var body=document.getElementById('modalBody');modal.classList.remove('hidden');body.innerHTML='<button class="close" data-close>×</button><div class="eyebrow">'+esc(t.phase)+'</div><h2>'+esc(t.name)+'</h2><p class="muted">'+t.mins+' min · '+(ready(t)?'disponível':'bloqueado')+' · '+taskPercent(t)+'%</p>'+bar(taskPercent(t))+'<div class="learning"><section><h3>O que você precisa dominar</h3><p>'+esc(l.goal)+'</p></section><section><h3>Estudar</h3>'+l.study.map(function(x){return '<p>• '+esc(x)+'</p>';}).join('')+'</section><section><h3>Praticar</h3>'+l.practice.map(function(x){return '<p>• '+esc(x)+'</p>';}).join('')+'</section><section><h3>Validar</h3>'+l.validate.map(function(x){return '<p>• '+esc(x)+'</p>';}).join('')+'</section><section><h3>Evidência</h3><p>'+esc(l.evidence)+'</p></section>'+(rs.length?'<section><h3>Material oficial</h3>'+rs.map(function(r){return '<p>• <a href="'+r.url+'" target="_blank" rel="noopener">'+esc(r.name)+'</a></p>';}).join('')+'</section>':'')+'</div>'+(t.pre.length?'<div class="dependencies"><h3>Pré-requisitos</h3>'+t.pre.map(function(x){var d=task(x);return '<div class="dependency '+(isDone(x)?'complete':'')+'">'+(isDone(x)?'✓':'○')+' '+esc(d?d.name:x)+'</div>';}).join('')+'</div>':'')+'<div class="stage-list">'+st.map(function(s,i){return '<button class="stage '+(stageComplete(t.id,i)?'complete':'')+'" data-stage="'+t.id+'" data-index="'+i+'" '+(!ready(t)&&!isDone(t.id)?'disabled':'')+'><b>'+(stageComplete(t.id,i)?'✓ ':'')+s+'</b><small>'+(['Conhecimento','Aplicação','Teste/validação','Evidência'][i]||'Validação')+'</small></button>';}).join('')+'</div><p class="muted">Só conclua uma etapa quando realmente conseguir demonstrá-la.</p>';}
function toggleStage(id,i){var t=task(id);if(!t||(!ready(t)&&!isDone(id)))return;var a=state.stageDone[id]||[];a[i]=!a[i];state.stageDone[id]=a;var st=stages(t),ok=true;for(var j=0;j<st.length;j++)if(!a[j])ok=false;if(ok){if(!isDone(id)){var at=new Date().toISOString();state.done[id]={at:at};state.history.push({id:id,at:at});}}else delete state.done[id];save();}
function reset(){if(confirm('Resetar todo o progresso?')){state=fresh();save();}}
function bind(){document.querySelectorAll('[data-view]').forEach(function(x){x.onclick=function(){render(x.getAttribute('data-view'));};});document.querySelectorAll('[data-open]').forEach(function(x){x.onclick=function(){taskDetail(x.getAttribute('data-open'));};});document.querySelectorAll('[data-close]').forEach(function(x){x.onclick=function(){document.getElementById('modal').classList.add('hidden');};});document.querySelectorAll('[data-stage]').forEach(function(x){x.onclick=function(){toggleStage(x.getAttribute('data-stage'),Number(x.getAttribute('data-index')));};});var m=document.getElementById('modal');if(m)m.onclick=function(e){if(e.target===m)m.classList.add('hidden');};var e=document.getElementById('english60');if(e)e.onclick=function(){state.english.minutes+=60;state.english.sessions++;save();};var r=document.getElementById('reset');if(r)r.onclick=reset;var ex=document.getElementById('export');if(ex)ex.onclick=function(){var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='iam-career-progress.json';a.click();};var im=document.getElementById('import');if(im)im.onclick=function(){document.getElementById('file').click();};var f=document.getElementById('file');if(f)f.onchange=function(){var reader=new FileReader();reader.onload=function(){try{state=JSON.parse(reader.result);save();}catch(err){alert('Arquivo inválido');}};reader.readAsText(f.files[0]);};}
function render(v){localStorage.setItem('iam-view',v);if(v==='roadmap')renderRoadmap();else if(v==='progress')renderProgress();else if(v==='certs')renderCerts();else if(v==='labs')renderLabs();else if(v==='settings')renderSettings();else renderToday();document.querySelectorAll('[data-view]').forEach(function(x){x.classList.toggle('active',x.getAttribute('data-view')===v);});bind();}
render(currentView());
})();
