(()=>{'use strict';
const KEY='cyber-hub-v3';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('cyber-hub-v2')||localStorage.getItem('cyber-hub-v1')||'{"topics":{},"sessions":[],"labs":{},"certs":{}}');
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const topics=()=>DOMAINS.flatMap(d=>d.topics.map((name,i)=>({id:`${d.id}-${i}`,name,domain:d.id,index:i})));
const topic=id=>topics().find(x=>x.id===id), domain=id=>DOMAINS.find(x=>x.id===id);
const pct=id=>{const c=state.topics[id]?.check||{};return Math.round(Object.values(c).filter(Boolean).length/6*100)};
const dp=d=>d?.topics?.length?Math.round(d.topics.reduce((a,_,i)=>a+pct(`${d.id}-${i}`),0)/d.topics.length):0;
const phases=[
 {n:'01',name:'Fundamentos',level:'Fundamental / Básico',desc:'Base técnica para toda a carreira.',domains:['fundamentals','crypto']},
 {n:'02',name:'Infraestrutura & Cloud',level:'Básico / Intermediário',desc:'Infraestrutura, redes, cloud e endpoints.',domains:['cloud','network','endpoint']},
 {n:'03',name:'Identidade & Acesso',level:'Intermediário',desc:'IAM, IGA e PAM.',domains:['iam','iga','pam']},
 {n:'04',name:'Defesa & Operações',level:'Intermediário / Avançado',desc:'SOC, resposta, vulnerabilidades, aplicações e dados.',domains:['soc','ir','vuln','appsec','data']},
 {n:'05',name:'Governança & Arquitetura',level:'Avançado / Especialista',desc:'GRC, arquitetura, resiliência, IA e ofensiva.',domains:['grc','architecture','resilience','ai','offensive']}
];
const pTopics=p=>p.domains.flatMap(id=>{const d=domain(id);return d?d.topics.map((name,i)=>({id:`${id}-${i}`,name,domain:id,index:i})):[]});
const pp=p=>{const a=p.domains.map(id=>dp(domain(id)));return a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):0};
const career=()=>{const a=DOMAINS.map(dp);return a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):0};
const currentPhase=()=>phases.find(p=>pp(p)<100)||phases.at(-1);
const nextTopic=()=>pTopics(currentPhase()).find(t=>pct(t.id)<100);
const level=(p,t)=>{const list=pTopics(p),pos=list.findIndex(x=>x.id===t.id);if(p.n==='01')return'Fundamental';return pos<Math.ceil(list.length*.35)?'Básico':pos<Math.ceil(list.length*.8)?'Intermediário':'Avançado'};
const bar=n=>`<div class="bar"><i style="width:${n}%"></i></div>`;
const icon=d=>`<span class="icon ${d?.color||''}">${d?.icon||'•'}</span>`;
function nav(){return `<aside><div class="logo">CYBER<span>HUB</span></div><div class="profile"><small>OBJETIVO PROFISSIONAL</small><b>Cloud · IAM · Security · GRC</b></div><button class="nav active" data-go="dashboard">Dashboard</button><button class="nav" data-go="labs">Laboratórios</button><button class="nav" data-go="certs">Certificações</button><div class="side-foot">AUTO SAVE · PROGRESSO LOCAL</div></aside>`}
function shell(c){document.body.innerHTML=`${nav()}<main><header class="top"><div class="page-nav"><button class="back" id="back">← Voltar</button><div><span class="kicker">CYBERSECURITY STUDY HUB</span><h1>${c.title}</h1><p>${c.sub||''}</p></div></div></header>${c.body}</main>`;$('#back').onclick=()=>{if(history.length>1)history.back();else go('dashboard')};document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));c.bind?.()}
function go(route){location.hash=route;render()}
function dashboard(){const p=currentPhase(),next=nextTopic();shell({title:'Dashboard',sub:'Seu mapa completo de conhecimento e acompanhamento profissional.',body:`<section class="career-overview"><div class="career-main"><span class="kicker">PROGRESSO DA CARREIRA</span><strong>${career()}%</strong>${bar(career())}<p>Todos os conteúdos possuem progresso individual e independente.</p></div><div class="current-module"><span class="kicker">MÓDULO ATUAL</span><b>Fase ${p.n} · ${esc(p.name)}</b><span>${esc(p.level)}</span>${bar(pp(p))}<strong>${pp(p)}%</strong>${next?`<button class="primary" data-topic="${next.id}">Continuar no próximo conteúdo →</button>`:''}</div></section><section class="section-head"><div><span class="kicker">MAPA COMPLETO</span><h2>Seu caminho</h2><p>Fases, áreas e todos os conhecimentos disponíveis. Clique em qualquer conteúdo para estudar.</p></div></section><section class="knowledge-map">${phases.map(phaseView).join('')}</section>`,bind})}
function phaseView(p){return `<article class="map-phase"><div class="map-phase-head"><span>${p.n}</span><div><span class="kicker">FASE ${p.n}</span><h2>${esc(p.name)}</h2><p>${esc(p.level)} · ${esc(p.desc)}</p></div><strong>${pp(p)}%</strong></div>${p.domains.map(id=>{const d=domain(id);if(!d)return'';return `<div class="map-domain"><div class="map-domain-title">${icon(d)}<div><b>${esc(d.name)}</b><small>${dp(d)}%</small></div></div><div class="knowledge-items">${d.topics.map((name,i)=>{const t={id:`${id}-${i}`,name};const n=String(i+1).padStart(2,'0');return `<button class="knowledge-item" data-topic="${t.id}"><span class="topic-number">${n}</span><b>${esc(name)}</b><small>${level(p,t)} · ${pct(t.id)}%</small>${bar(pct(t.id))}</button>`}).join('')}</div></div>`}).join('')}</article>`}
function topicView(id){const t=topic(id);if(!t)return go('dashboard');const d=domain(t.domain),p=phases.find(x=>x.domains.includes(t.domain))||phases[0],s=state.topics[id]||{};const checks=['Conceito e terminologia','Documentação oficial / arquitetura','Implementação prática','Troubleshooting controlado','Registrar evidência objetiva','Explicar sem consulta'];shell({title:t.name,sub:`Fase ${p.n} · ${d.name} · ${level(p,t)} · ${pct(id)}%`,body:`<div class="topic-detail"><div class="panel"><span class="kicker">ESTUDO DESTE CONTEÚDO</span><h2>Estudar → Praticar → Evidenciar → Validar</h2><div class="checklist">${checks.map((x,i)=>`<label><input type="checkbox" data-check="${i}" ${s.check?.[i]?'checked':''}>${x}</label>`).join('')}</div><div class="progress-live" id="topic-progress"><strong>${pct(id)}%</strong> concluído</div><textarea id="note" placeholder="Notas, comandos, evidências, links…">${esc(s.note||'')}</textarea><button class="primary" id="save">Salvar estudo</button></div><div class="panel"><span class="kicker">CONTEXTO</span><div class="plain-row">Fase ${p.n} · ${esc(p.name)}</div><div class="plain-row">Nível: ${level(p,t)}</div><div class="plain-row">Área: ${esc(d.name)}</div><span class="kicker gap">CERTIFICAÇÕES RELACIONADAS</span>${(d.certs||[]).map(x=>`<div class="cert-chip">${esc(x)}</div>`).join('')||'<div class="plain-row">Sem certificação direta.</div>'}</div></div>`,bind:()=>{const els=[...document.querySelectorAll('[data-check]')];const sync=()=>{const x=state.topics[id]||{};x.check=x.check||{};els.forEach((e,i)=>x.check[i]=e.checked);state.topics[id]=x;save();$('#topic-progress').innerHTML=`<strong>${pct(id)}%</strong> concluído`;};els.forEach(e=>e.onchange=sync);$('#save').onclick=()=>{const x=state.topics[id]||{};x.note=$('#note').value;state.topics[id]=x;save()}}})}
function labs(){shell({title:'Laboratórios',sub:'Prática concreta e acompanhamento independente.',body:`<section class="lab-grid">${DOMAINS.map(d=>`<div class="panel"><span class="kicker">${esc(d.name)}</span>${(SPECIALS?.[d.id]?.labs||[`Lab introdutório de ${d.name}`,`Cenário prático de ${d.name}`]).map((x,i)=>{const id=`${d.id}-lab-${i}`,done=state.labs?.[id];return `<button class="lab-row ${done?'done':''}" data-lab="${id}"><span>${done?'✓':'○'}</span>${esc(x)}</button>`}).join('')}</div>`).join('')}</section>`,bind:()=>{document.querySelectorAll('[data-lab]').forEach(b=>b.onclick=()=>{state.labs=state.labs||{};state.labs[b.dataset.lab]=!state.labs[b.dataset.lab];save();labs()})}})}
function certs(){shell({title:'Certificações',sub:'Roadmap de certificações relacionado ao conhecimento do mapa.',body:`<section class="cert-grid">${(typeof CERTS==='undefined'?[]:CERTS).map(c=>{const d=domain(c.domain);return `<article class="cert-card"><div class="cert-top"><b>${esc(c.name)}</b><span>${esc(c.level||'')}</span></div><h2>${esc(c.title)}</h2><p>${esc(c.provider||'')}</p>${d?bar(dp(d)):''}<div class="cert-foot"><span>Conhecimentos relacionados</span><strong>${d?dp(d):0}%</strong></div></article>`}).join('')}</section>`})}
function render(){const r=location.hash.slice(1)||'dashboard';if(r==='dashboard'||r==='map'||r==='study')dashboard();else if(r==='labs')labs();else if(r==='certs')certs();else if(r.startsWith('topic/'))topicView(r.slice(6));else renderDashboardFallback()}
function renderDashboardFallback(){dashboard()}
window.addEventListener('hashchange',render);render();
})();
