(function(){
'use strict';
var KEY='iam-career-hub-state-v9', LEGACY='iam-hub-individual-tasks-v10';
var data=window.ROADMAP||{career:{target:'IAM Analyst / IAM Engineer'},phases:[]};
var learning=window.LEARNING||{}, certs=window.CERTIFICATIONS||{};
var app=document.getElementById('app');
function fresh(){return {done:{},activityDone:{},evidence:{},english:{minutes:0,sessions:0},history:[],started:new Date().toISOString()};}
function load(){var s=fresh();try{s=Object.assign(s,JSON.parse(localStorage.getItem(KEY)||'{}')||{});}catch(e){};s.done=s.done||{};s.activityDone=s.activityDone||{};s.evidence=s.evidence||{};s.english=s.english||{minutes:0,sessions:0};s.history=s.history||[];try{var old=JSON.parse(localStorage.getItem(LEGACY)||'{}')||{};Object.keys(old).forEach(function(k){if(old[k]===true&&!s.activityDone[k])s.activityDone[k]=true;});}catch(e){};return s;}
var state=load();
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function tasks(){var a=[];(data.phases||[]).forEach(function(p){(p.tasks||[]).forEach(function(t){a.push({id:t.id,name:t.name,type:t.type||'knowledge',mins:t.mins||60,pre:t.pre||[],phaseId:p.id,phase:p.name,goal:t.goal||''});});});return a;}
function get(id){return tasks().find(function(t){return t.id===id;});}
function detail(t){var l=learning.enrich?learning.enrich(t):{};return {goal:l.goal||'Dominar a competência.',study:l.study||['Estudar documentação oficial.'],practice:l.practice||['Executar a prática.'],validate:l.validate||['Explicar sem consulta e resolver um cenário.'],evidence:l.evidence||'Registrar evidência objetiva.'};}
function stages(t){if(t.type==='lab')return [{n:'Estudar',items:detail(t).study},{n:'Executar',items:detail(t).practice},{n:'Troubleshoot',items:['Provocar um erro controlado.','Diagnosticar a causa.']},{n:'Evidenciar',items:[detail(t).evidence]}];if(t.type==='validate')return [{n:'Resolver',items:['Resolver o cenário sem tutorial.']},{n:'Explicar',items:['Explicar sem consulta.']},{n:'Registrar',items:[detail(t).evidence]}];var d=detail(t);return [{n:'Estudar',items:d.study},{n:'Praticar',items:d.practice},{n:'Recapitular',items:['Explicar os conceitos sem consultar.','Reconstruir o fluxo ou arquitetura.','Listar erros e correções.','Explicar onde isso é usado em produção.']},{n:'Validar',items:d.validate}];}
function key(id,s,i){return id+'|'+s+'|'+i;}
function isDone(id,s,i){return state.activityDone[key(id,s,i)]===true;}
function stagePct(t,s){var x=stages(t)[s]||{items:[]},n=x.items.length,d=0;for(var i=0;i<n;i++)if(isDone(t.id,s,i))d++;return n?Math.round(d*100/n):0;}
function taskPct(t){var ss=stages(t),d=0,n=0;ss.forEach(function(x,s){n+=x.items.length;for(var i=0;i<x.items.length;i++)if(isDone(t.id,s,i))d++;});return n?Math.round(d*100/n):0;}
function complete(t){return taskPct(t)===100;}
function ready(t){return (t.pre||[]).every(function(id){return !!state.done[id];});}
function sync(t){if(complete(t)){if(!state.done[t.id])state.history.push({id:t.id,at:new Date().toISOString()});state.done[t.id]={at:(state.done[t.id]&&state.done[t.id].at)||new Date().toISOString()};}else delete state.done[t.id];}
function next(){var a=tasks();for(var i=0;i<a.length;i++)if(!complete(a[i])&&!state.done[a[i].id]&&ready(a[i]))return a[i];for(var j=0;j<a.length;j++)if(!complete(a[j])&&!state.done[a[j].id])return a[j];return null;}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function bar(v){return '<div class="bar"><i style="width:'+v+'%"></i></div>';}
function nav(){return '<nav>'+[['today','Today'],['roadmap','Roadmap'],['progress','Progress'],['certs','Certificações'],['labs','Labs'],['settings','Config']].map(function(x){return '<button data-view="'+x[0]+'">'+x[1]+'</button>';}).join('')+'</nav>';}
function shell(content){app.innerHTML='<div class="app-shell"><aside class="sidebar"><div class="brand"><strong>IAM</strong><span>CAREER HUB</span></div><div class="career-chip"><span>OBJETIVO</span><b>'+esc(data.career.target)+'</b><small>Cloud IAM</small></div>'+nav()+'<div class="sidebar-foot"><span>3h conteúdo</span><span>1h inglês</span></div></aside><main>'+content+'</main></div>';bindNav();}
function head(k,t,s){return '<header class="top"><div><div class="eyebrow">'+k+'</div><h1>'+esc(t)+'</h1><p>'+esc(s||'')+'</p></div></header>';}
function renderToday(){state=load();var t=next(),focus=t?'<section class="today-focus"><span class="focus-label">'+esc(t.phase)+'</span><h2>'+esc(t.name)+'</h2><p>'+t.mins+' min · '+taskPct(t)+'%</p><div class="today-exec"><span>Execução: '+taskPct(t)+'%</span><span>Modo: '+(t.type==='lab'?'laboratório':t.type==='validate'?'validação':'guiado')+'</span></div><button class="primary" data-task="'+esc(t.id)+'">Continuar →</button></section>':'<section class="today-focus"><h2>Trilha concluída</h2><p>Revise as evidências e avance para a próxima meta.</p></section>';var a=tasks(),next2=null;if(t){var ix=a.findIndex(function(x){return x.id===t.id;});for(var i=ix+1;i<a.length;i++)if(!state.done[a[i].id]&&ready(a[i])){next2=a[i];break;}}shell(head('TODAY',t?'Faça agora':'Tudo concluído','Uma ação por vez.')+focus+(next2?'<section class="today-next"><span>PRÓXIMO</span><b>'+esc(next2.name)+'</b></section>':'')+'<section class="today-routine"><span>3h conteúdo</span><span>1h inglês</span></section>');bindActions();}
function renderRoadmap(){state=load();var h='';(data.phases||[]).forEach(function(p){var d=p.tasks.filter(function(t){return state.done[t.id];}).length;h+='<details class="phase-card"><summary><div><b>'+esc(p.id)+' · '+esc(p.name)+'</b><small>'+d+'/'+p.tasks.length+'</small></div><strong>'+Math.round(d*100/(p.tasks.length||1))+'%</strong></summary>'+bar(Math.round(d*100/(p.tasks.length||1)))+'<div class="phase-tasks">'+p.tasks.map(function(t){return '<div class="task '+(state.done[t.id]?'done':'')+'"><div><b>'+esc(t.name)+'</b><small>'+t.mins+' min · '+(state.done[t.id]?'concluído':ready(t)?taskPct(t)+'%':'bloqueado')+'</small></div><button data-task="'+esc(t.id)+'">Abrir</button></div>';}).join('')+'</div></details>';});shell(head('ROADMAP','Seu caminho','Básico → intermediário → avançado.')+'<section class="roadmap-list">'+h+'</section>');bindActions();}
function renderProgress(){state=load();var a=tasks(),d=a.filter(function(t){return state.done[t.id];}).length;var domains=(data.phases||[]).map(function(p){var n=p.tasks.filter(function(t){return state.done[t.id];}).length,v=Math.round(n*100/(p.tasks.length||1));return '<div class="domain"><div><span>'+esc(p.name)+'</span><b>'+v+'%</b></div>'+bar(v)+'</div>';}).join('');shell(head('PROGRESS','Progresso','Somente competências concluídas.')+'<section class="progress-hero"><div class="big-number">'+Math.round(d*100/(a.length||1))+'%</div>'+bar(Math.round(d*100/(a.length||1)))+'<span>'+d+' de '+a.length+' competências</span></section><section class="domain-list">'+domains+'</section><section class="panel english-panel"><div><h3>Inglês técnico</h3><p>'+state.english.sessions+' sessões · '+state.english.minutes+' min</p></div><button class="primary" id="english60">+ 60 min</button></section>');bindActions();}
function renderCerts(){var all=certs.tracks||[];var h='<section class="cert-path panel"><div class="eyebrow">ORDEM</div><h2>SC-900 → AZ-900 → SC-300 → AZ-104 conforme vaga → AWS SAA → AWS Security</h2><p>Certificação acompanha a prática.</p></section>';['Básico','Intermediário','Avançado'].forEach(function(level){var list=all.filter(function(c){var l=(c.level==='Fundamental'||c.level==='Foundational')?'Básico':(c.level==='Associate'||c.level==='Professional')?'Intermediário':'Avançado';return l===level;});if(list.length)h+='<section class="cert-section"><h2>'+level+'</h2><div class="cert-grid">'+list.map(function(c){return '<article class="cert-card"><h3>'+esc(c.name)+'</h3><small>'+esc(c.provider||'')+'</small><p>'+esc(c.why||'')+'</p></article>';}).join('')+'</div></section>';});shell(head('CERTIFICAÇÕES','Trilha de certificações','Prioridade IAM e Cloud.')+h);}
function renderLabs(){shell(head('LABS','Laboratórios','Prática que gera evidência.')+'<section class="content-grid"><div class="panel"><h3>Existentes</h3><div class="evidence"><b>Cloud Security</b><span>Azure · Entra ID · RBAC · VNet · NSG · VM</span></div><div class="evidence"><b>On-Premises</b><span>AD · DNS · DHCP · GPO · Wazuh · Suricata</span></div></div><div class="panel"><h3>Próximos</h3>'+['Hybrid Identity','Enterprise SSO','PIM + Governance','Graph Automation','Entra → AWS Federation','IAM Architecture'].map(function(x){return '<div class="evidence"><b>'+x+'</b></div>';}).join('')+'</div></section>');}
function renderSettings(){shell(head('CONFIG','Configurações','Dados e rotina.')+'<section class="panel settings"><div class="setting"><span>Objetivo</span><b>'+esc(data.career.target)+'</b></div><div class="setting"><span>Rotina</span><b>3h conteúdo + 1h inglês</b></div><div class="actions"><button class="secondary" id="export">Exportar</button><button class="secondary" id="import">Importar</button><button class="danger" id="reset">Resetar</button><input id="file" type="file" accept="application/json" hidden></div></section>');bindActions();}
function renderTask(id){state=load();var t=get(id);if(!t){renderToday();return;}var ss=stages(t),d=detail(t);var html='<div class="task-page"><div class="back-row"><button class="secondary" id="back">← Today</button><span>'+esc(t.phase)+'</span></div><div class="task-page-head"><div class="eyebrow">'+esc(t.id)+'</div><h1>'+esc(t.name)+'</h1><p>'+t.mins+' min · '+taskPct(t)+'% · '+(ready(t)?'disponível':'bloqueada')+'</p></div><div class="task-page-grid"><article class="panel learning-panel"><section><h2>Objetivo</h2><p>'+esc(d.goal)+'</p></section>'+ss.map(function(st,s){return '<section><h2>'+esc(st.n)+'</h2>'+st.items.map(function(x,i){var done=isDone(t.id,s,i);return '<p class="detail-line '+(done?'individual-task-done':'')+'" data-activity="'+esc(key(t.id,s,i))+'"><span class="check">'+(done?'✓':'○')+'</span>'+esc(x)+'</p>';}).join('')+'</section>';}).join('')+'<section><h2>Evidência</h2><p>'+esc(d.evidence)+'</p></section></article><aside class="task-page-side"><div class="panel"><h2>Execução</h2>'+ss.map(function(st,s){return '<div class="stage '+(stagePct(t,s)===100?'complete':'')+'"><b>'+esc(st.n)+'</b><small>'+stagePct(t,s)+'%</small></div>';}).join('')+'</div><div class="panel"><label class="evidence-input"><span>Nota / evidência</span><textarea id="evidenceText" rows="5" placeholder="Comando, resultado ou link.">'+esc(state.evidence[t.id]||'')+'</textarea><button class="secondary" id="saveEvidence">Salvar</button></label></div></aside></div></div>';shell(html);bindTask(id);}
function bindTask(id){var b=document.getElementById('back');if(b)b.onclick=function(){renderToday();};document.querySelectorAll('[data-activity]').forEach(function(x){x.onclick=function(){var p=x.getAttribute('data-activity').split('|');state=load();state.activityDone[x.getAttribute('data-activity')]=!state.activityDone[x.getAttribute('data-activity')];sync(get(id));save();renderTask(id);};});var s=document.getElementById('saveEvidence');if(s)s.onclick=function(){state=load();state.evidence[id]=document.getElementById('evidenceText').value;save();renderTask(id);};}
function bindActions(){document.querySelectorAll('[data-task]').forEach(function(x){x.onclick=function(){renderTask(x.getAttribute('data-task'));};});var e=document.getElementById('english60');if(e)e.onclick=function(){state=load();state.english.minutes+=60;state.english.sessions++;save();renderProgress();};var r=document.getElementById('reset');if(r)r.onclick=function(){if(confirm('Resetar todo o progresso?')){state=fresh();save();renderToday();}};var ex=document.getElementById('export');if(ex)ex.onclick=function(){var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(load(),null,2)],{type:'application/json'}));a.download='iam-career-progress.json';a.click();};var im=document.getElementById('import');if(im)im.onclick=function(){document.getElementById('file').click();};var f=document.getElementById('file');if(f)f.onchange=function(){var reader=new FileReader();reader.onload=function(){try{state=JSON.parse(reader.result);save();renderToday();}catch(e){alert('Arquivo inválido.');}};reader.readAsText(f.files[0]);};}
function bindNav(){document.querySelectorAll('[data-view]').forEach(function(x){x.onclick=function(){render(x.getAttribute('data-view'));};});}
function render(view){state=load();if(view==='roadmap')renderRoadmap();else if(view==='progress')renderProgress();else if(view==='certs')renderCerts();else if(view==='labs')renderLabs();else if(view==='settings')renderSettings();else renderToday();}
window.addEventListener('hashchange',function(){var h=location.hash.slice(1);if(h.indexOf('task/')===0)renderTask(decodeURIComponent(h.slice(5)));else render('today');});
render('today');
})();
