(function(){'use strict';
const KEY='iam-career-hub-state-v11', MIG='iam-career-hub-migrations-v3';
const data=window.ROADMAP||{career:{target:'IAM Analyst / IAM Engineer'},phases:[]};
const learning=window.LEARNING||{}; const certs=window.CERTIFICATIONS||{}; const app=document.getElementById('app');
const fresh=()=>({activityDone:{},evidence:{},mastery:{},reviews:{},sessions:[],english:{minutes:0,sessions:0},history:[],started:new Date().toISOString()});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=()=>Date.now(), day=86400000, k=(id,s,i)=>`${id}|${s}|${i}`;
function norm(s){s=Object.assign(fresh(),s||{}); for(const x of ['activityDone','evidence','mastery','reviews'])if(!s[x]||typeof s[x]!=='object')s[x]={}; if(!Array.isArray(s.sessions))s.sessions=[]; if(!Array.isArray(s.history))s.history=[]; if(!s.english||typeof s.english!=='object')s.english={minutes:0,sessions:0}; s.english.minutes=+s.english.minutes||0;s.english.sessions=+s.english.sessions||0;return s}
function load(){try{return norm(JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return fresh()}} function save(s){try{localStorage.setItem(KEY,JSON.stringify(norm(s)));return true}catch(e){return false}}
let state=load();
function tasks(){const a=[];(data.phases||[]).forEach(p=>(p.tasks||[]).forEach(t=>a.push({...t,phaseId:p.id,phase:p.name,mins:+t.mins||60,pre:t.pre||[]})));return a} const get=id=>tasks().find(t=>t.id===id);
function detail(t){const l=learning.enrich?learning.enrich(t):{};return{goal:l.goal||t.goal||'Dominar a competência.',study:Array.isArray(l.study)&&l.study.length?l.study:['Estudar documentação oficial e conceitos fundamentais.'],practice:Array.isArray(l.practice)&&l.practice.length?l.practice:['Executar a prática proposta.'],validate:Array.isArray(l.validate)&&l.validate.length?l.validate:['Explicar sem consulta e resolver um cenário.'],evidence:l.evidence||'Registrar evidência objetiva.'}}
function stages(t){const d=detail(t);if(t.type==='lab')return[{n:'Estudar',items:d.study},{n:'Executar',items:d.practice},{n:'Troubleshoot',items:['Provocar um erro controlado.','Diagnosticar a causa e corrigir.']},{n:'Evidenciar',items:[d.evidence]}];if(t.type==='validate')return[{n:'Resolver',items:['Resolver o cenário sem tutorial.']},{n:'Explicar',items:['Explicar sem consulta e justificar a decisão.']},{n:'Registrar',items:[d.evidence]}];return[{n:'Estudar',items:d.study},{n:'Praticar',items:d.practice},{n:'Recapitular',items:['Explicar os conceitos sem consultar.','Reconstruir o fluxo ou arquitetura.','Listar erros e correções.','Explicar onde isso é usado em produção.']},{n:'Validar',items:d.validate}]}
function done(t,s,i){return state.activityDone[k(t.id,s,i)]===true} function metrics(t){let total=0,dn=0;stages(t).forEach((st,si)=>st.items.forEach((_,i)=>{total++;if(done(t,si,i))dn++}));return{total,done:dn,pct:total?Math.round(dn*100/total):0}}
function ready(t){return(t.pre||[]).every(id=>metrics(get(id)||{id,phase:'',mins:1}).pct===100)}
const intervals=[1,3,7,14,30,60];
function reviewInfo(t){return state.reviews[t.id]||null} function due(t){const r=reviewInfo(t);return r&&r.next<=now()} function mastery(t){const m=state.mastery[t.id];return m&&Number.isFinite(m.score)?m.score:null}
function sync(t,s){const m=metrics(t);if(m.pct===100&&!s.reviews[t.id])s.reviews[t.id]={level:0,next:now()+day};if(m.pct<100){delete s.reviews[t.id];delete s.mastery[t.id]}}
function recordValidation(t,s,score){score=Math.max(0,Math.min(100,+score||0));const old=s.mastery[t.id];s.mastery[t.id]={score,at:new Date().toISOString()};let r=s.reviews[t.id]||{level:0};if(score>=70){r.level=Math.min(intervals.length-1,(r.level||0)+1)}else{r.level=0}r.next=now()+intervals[r.level]*day;r.lastScore=score;r.lastAt=new Date().toISOString();s.reviews[t.id]=r;s.history.push({id:t.id,type:'validation',score,at:new Date().toISOString()})}
function overall(){let a=tasks(),x=0,n=0;a.forEach(t=>{const m=metrics(t);x+=m.done;n+=m.total});return n?Math.round(x*100/n):0} function phasePct(p){let x=0,n=0;(p.tasks||[]).forEach(t=>{const m=metrics(t);x+=m.done;n+=m.total});return n?Math.round(x*100/n):0}
function dueReviews(){return tasks().filter(t=>due(t))} function nextTask(){const a=tasks(),r=dueReviews();return r[0]||a.find(t=>metrics(t).pct<100&&ready(t))||a.find(t=>metrics(t).pct<100)||null}
function bar(v){return`<div class="bar"><i style="width:${Math.max(0,Math.min(100,v))}%"></i></div>`}
function nav(){return'<nav>'+[['today','Today'],['roadmap','Roadmap'],['certs','Certificações'],['labs','Labs'],['settings','Config']].map(([a,b])=>`<button type="button" data-view="${a}">${b}</button>`).join('')+'</nav>'}
function shell(c){app.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><strong>IAM</strong><span>CAREER HUB</span></div><div class="career-chip"><span>OBJETIVO</span><b>${esc(data.career.target)}</b><small>Cloud IAM</small></div>${nav()}<div class="sidebar-foot"><span>3h conteúdo</span><span>1h inglês</span></div></aside><main>${c}</main></div>`;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view))}
function head(k,t,s){return`<header class="top"><div><div class="eyebrow">${esc(k)}</div><h1>${esc(t)}</h1><p>${esc(s||'')}</p></div></header>`}
function go(r){const h='#'+r; if(location.hash===h){render(r);return} history.pushState({r},'',h);render(r)}
function renderToday(){state=load();const due=dueReviews(),t=nextTask();let c='';if(due.length)c+=`<section class="alert-panel"><b>REVISÕES VENCIDAS</b><span>${due.length} competência(s) aguardando retenção.</span></section>`;if(t){const m=metrics(t),r=reviewInfo(t);c+=`<section class="today-focus"><span class="focus-label">${esc(t.phase)}</span><h2>${esc(t.name)}</h2><p>${r&&r.next<=now()?'Revisão · ':''}${t.mins} min · ${m.pct}% execução</p>${bar(m.pct)}<div class="today-exec"><span>Execução ${m.pct}%</span><span>${mastery(t)==null?'Domínio não validado':'Domínio '+mastery(t)+'%'}</span></div><button type="button" class="primary" data-task="${esc(t.id)}">${r&&r.next<=now()?'Revisar →':m.pct?'Continuar →':'Começar →'}</button></section>`}else c+='<section class="today-focus"><h2>Trilha concluída</h2><p>Todas as competências possuem execução registrada.</p></section>';const mins=Math.min(180,state.sessions.filter(x=>new Date(x.at).toDateString()===new Date().toDateString()).reduce((a,x)=>a+x.minutes,0));c+=`<section class="today-routine"><div><b>Conteúdo</b><span>${mins} / 180 min</span>${bar(mins/180*100)}</div><div><b>Inglês</b><span>${Math.min(60,state.english.minutes%61)} / 60 min</span>${bar(Math.min(100,(state.english.minutes%60)/60*100))}</div></section>`;shell(head('TODAY','Faça agora','Revisão → competência → prática → validação.')+c);bindCommon()}
function renderRoadmap(){state=load();let h=`<section class="roadmap-overview"><div><span>EXECUÇÃO GERAL</span><strong>${overall()}%</strong></div>${bar(overall())}<small>Derivado das etapas reais concluídas.</small></section>`;(data.phases||[]).forEach(p=>{const v=phasePct(p);h+=`<details class="phase-card"><summary><div><b>${esc(p.id)} · ${esc(p.name)}</b><small>${v}% · ${(p.tasks||[]).length} competências</small></div><strong>${v}%</strong></summary>${bar(v)}<div class="phase-tasks">${(p.tasks||[]).map(t=>{const m=metrics(t),ms=mastery(t),r=reviewInfo(t);return`<div class="task ${m.pct===100?'done':''}"><div class="task-main"><b>${esc(t.name)}</b><small>${m.pct}% execução · ${ms==null?'domínio —':`domínio ${ms}%`}${r&&r.next<=now()?' · revisão vencida':''}</small>${bar(m.pct)}</div><button type="button" data-task="${esc(t.id)}">${r&&r.next<=now()?'Revisar':m.pct===100?'Revisar':'Abrir'}</button></div>`}).join('')}</div></details>`});shell(head('ROADMAP','Seu caminho','Básico → intermediário → avançado.')+'<section class="roadmap-list">'+h+'</section>');bindCommon()}
function renderTask(id){state=load();const t=get(id);if(!t){go('today');return}const ss=stages(t),m=metrics(t),ms=mastery(t),r=reviewInfo(t);let html=`<div class="task-page"><div class="back-row"><button type="button" class="secondary" id="back">← Today</button><span>${esc(t.phase)}</span></div><div class="task-page-head"><div class="eyebrow">${esc(t.id)}</div><h1>${esc(t.name)}</h1><p>${m.pct}% execução · ${ms==null?'domínio não validado':'domínio '+ms+'%'} · ${r&&r.next<=now()?'revisão vencida':r?'próxima revisão em '+Math.max(0,Math.ceil((r.next-now())/day))+'d':'validação ainda não agendada'}</p>${bar(m.pct)}</div><div class="task-page-grid"><article class="panel learning-panel"><section><h2>Objetivo</h2><p>${esc(detail(t).goal)}</p></section>${ss.map((st,si)=>`<section><h2>${esc(st.n)}</h2>${st.items.map((x,i)=>{const d=done(t,si,i);return`<button type="button" class="detail-line activity-toggle ${d?'individual-task-done':''}" data-activity="${esc(k(t.id,si,i))}" aria-pressed="${d}"><span class="check">${d?'✓':'○'}</span><span>${esc(x)}</span></button>`}).join('')}</section>`).join('')}<section><h2>Evidência</h2><textarea id="evidenceText" rows="5" placeholder="Comando, resultado, link ou observação.">${esc(state.evidence[t.id]||'')}</textarea><button type="button" class="secondary" id="saveEvidence">Salvar evidência</button></section></article><aside class="task-page-side"><div class="panel"><h2>Execução</h2>${ss.map((st,si)=>{const n=st.items.length,dn=st.items.filter((_,i)=>done(t,si,i)).length,p=n?Math.round(dn*100/n):0;return`<div class="stage ${p===100?'complete':''}"><b>${esc(st.n)}</b><small>${p}%</small></div>`}).join('')}</div><div class="panel"><h2>Domínio</h2><p>Valide sem tutorial. 70%+ avança a revisão.</p><input id="score" type="number" min="0" max="100" value="${ms??''}" placeholder="0–100"><button type="button" class="primary" id="validate">Registrar validação</button></div></aside></div></div>`;shell(html);document.getElementById('back').onclick=()=>go('today');document.querySelectorAll('[data-activity]').forEach(x=>x.onclick=()=>{const kk=x.dataset.activity;const s=load();s.activityDone[kk]=!s.activityDone[kk];sync(t,s);save(s);state=load();renderTask(id)});document.getElementById('saveEvidence').onclick=()=>{const s=load();s.evidence[id]=document.getElementById('evidenceText').value;save(s);state=load();renderTask(id)};document.getElementById('validate').onclick=()=>{const s=load();recordValidation(t,s,document.getElementById('score').value);save(s);state=load();renderTask(id)}}
function renderCerts(){const all=certs.tracks||[];let h='<section class="cert-path panel"><div class="eyebrow">ORDEM</div><h2>SC-900 → AZ-900 → SC-300 → AZ-104 conforme vaga → AWS</h2><p>Certificação acompanha competência prática.</p></section>';['Básico','Intermediário','Avançado'].forEach(l=>{const a=all.filter(c=>c.level&&((c.level==='Fundamental'||c.level==='Foundational')?'Básico':(c.level==='Associate'||c.level==='Professional')?'Intermediário':'Avançado')===l);if(a.length)h+=`<section class="cert-section"><h2>${l}</h2><div class="cert-grid">${a.map(c=>`<article class="cert-card"><h3>${esc(c.name)}</h3><small>${esc(c.provider||'')}</small><p>${esc(c.why||'')}</p></article>`).join('')}</div></section>`});shell(head('CERTIFICAÇÕES','Trilha de certificações','Prioridade IAM e Cloud.')+h)}
function renderLabs(){shell(head('LABS','Laboratórios','Prática que gera evidência.')+'<section class="content-grid"><div class="panel"><h3>Existentes</h3><div class="evidence"><b>Cloud Security</b><span>Azure · Entra ID · RBAC · VNet · NSG · VM</span></div><div class="evidence"><b>On-Premises</b><span>AD · DNS · DHCP · GPO · Wazuh · Suricata</span></div></div><div class="panel"><h3>Próximos</h3>'+['Hybrid Identity','Enterprise SSO','PIM + Governance','Graph Automation','Entra → AWS Federation','IAM Architecture'].map(x=>`<div class="evidence"><b>${x}</b></div>`).join('')+'</div></section>')}
function renderSettings(){shell(head('CONFIG','Configurações','Estado, rotina e backup.')+'<section class="panel settings"><div class="setting"><span>Objetivo</span><b>${esc(data.career.target)}</b></div><div class="setting"><span>Rotina</span><b>3h conteúdo + 1h inglês</b></div><div class="actions"><button class="secondary" id="english">+60 min inglês</button><button class="secondary" id="export">Exportar</button><button class="secondary" id="import">Importar</button><button class="danger" id="reset">Resetar</button><input id="file" type="file" accept="application/json" hidden></div></section>');document.getElementById('english').onclick=()=>{const s=load();s.english.minutes+=60;s.english.sessions++;save(s);renderSettings()};document.getElementById('export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(load(),null,2)],{type:'application/json'}));a.download='iam-career-hub-progress.json';a.click()};const f=document.getElementById('file');document.getElementById('import').onclick=()=>f.click();f.onchange=()=>{const r=new FileReader();r.onload=()=>{try{save(JSON.parse(r.result));state=load();renderToday()}catch(e){alert('Arquivo inválido.')}};r.readAsText(f.files[0])};document.getElementById('reset').onclick=()=>{if(confirm('Apagar todo o progresso?')){localStorage.removeItem(KEY);state=load();renderToday()}}}
function bindCommon(){document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>go('task/'+b.dataset.task))}
function render(r){state=load();if(r==='today')renderToday();else if(r==='roadmap')renderRoadmap();else if(r==='certs')renderCerts();else if(r==='labs')renderLabs();else if(r==='settings')renderSettings();else if(r.startsWith('task/'))renderTask(r.slice(5));else go('today')}
window.addEventListener('popstate',()=>render(location.hash.slice(1)||'today'));window.addEventListener('hashchange',()=>render(location.hash.slice(1)||'today'));render(location.hash.slice(1)||'today');
})();
