const KEY='iam-career-hub-state-v4';
const data=window.ROADMAP,app=document.getElementById('app');
const allTasks=()=>data.phases.flatMap(p=>p.tasks.map(t=>({...t,phaseId:p.id,phase:p.name,goal:p.goal}))),taskById=id=>allTasks().find(t=>t.id===id),phaseById=id=>data.phases.find(p=>p.id===id);
const stagesFor=t=>t.type==='lab'?['Estudar','Executar','Troubleshoot','Evidenciar']:t.type==='validate'?['Resolver cenário','Explicar sem consulta','Registrar validação']:['Estudar','Praticar','Recapitular','Validar'];
const blankState=()=>({stageDone:{},done:{},english:{minutes:0,sessions:0},history:[],started:new Date().toISOString()});
let state=JSON.parse(localStorage.getItem(KEY)||'null')||blankState();if(!state.stageDone)state.stageDone={};if(!state.done)state.done={};
const pct=(a,b)=>b?Math.round(a/b*100):0,done=id=>!!state.done[id],stageDone=(id,i)=>!!(state.stageDone[id]||[])[i],taskPct=t=>pct((state.stageDone[t.id]||[]).filter(Boolean).length,stagesFor(t).length),ready=t=>(t.pre||[]).every(done),completed=()=>allTasks().filter(t=>done(t.id)),overall=()=>pct(completed().length,allTasks().length);
const phaseStats=p=>{const d=p.tasks.filter(t=>done(t.id)).length;return{done:d,total:p.tasks.length,pct:pct(d,p.tasks.length)}},currentStage=t=>{const s=stagesFor(t),i=s.findIndex((_,n)=>!stageDone(t.id,n));return i<0?s.length-1:i},nextTask=()=>allTasks().find(t=>!done(t.id)&&ready(t))||null,upcoming=()=>allTasks().filter(t=>!done(t.id)&&ready(t)).slice(0,5),currentView=()=>localStorage.getItem('iam-view')||'today';
const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));render(currentView())};
function completeStage(id,i){const t=taskById(id);if(!t||(!ready(t)&&!done(id)))return;const s=state.stageDone[id]||[];s[i]=!s[i];state.stageDone[id]=s;if(s.length>=stagesFor(t).length&&s.every(Boolean)&&!done(id)){const at=new Date().toISOString();state.done[id]={at};state.history.push({id,at})}else if(!s.every(Boolean)&&done(id))delete state.done[id];save()}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function header(k,t,s=''){return `<header class="top"><div><div class="eyebrow">${k}</div><h1>${esc(t)}</h1>${s?`<p>${esc(s)}</p>`:''}</div><time>${new Date().toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'})}</time></header>`}function nav(){return `<nav>${[['today','Today'],['roadmap','Roadmap'],['progress','Progress'],['certs','Certificações'],['labs','Labs'],['settings','Config']].map(([id,l])=>`<button class="nav-btn" data-view="${id}">${l}</button>`).join('')}</nav>`}function shell(c){app.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><strong>IAM</strong><span>CAREER HUB</span></div><div class="career-chip"><span>Objetivo</span><b>IAM Engineer</b><small>Cloud IAM</small></div>${nav()}<div class="sidebar-foot"><span>2h estudo</span><span>1h inglês</span></div></aside><main>${c}</main></div><div id="modal" class="modal hidden"><div class="modal-card" id="modalBody"></div></div>`}function bar(v){return `<div class="bar"><i style="width:${v}%"></i></div>`}
function taskRow(t){const d=done(t.id),p=taskPct(t);return `<div class="task ${d?'done':''}"><div><b>${d?'✓ ':''}${esc(t.name)}</b><small>${t.mins} min · ${d?'concluído':ready(t)?(p?`${p}% validado`:'disponível'):'bloqueado'}</small></div><div class="task-actions"><button class="icon-btn" data-open="${t.id}">Abrir</button></div></div>`}
function renderToday(){const t=nextTask(),p=t?phaseById(t.phaseId):null,up=upcoming(),tm=state.history.filter(h=>new Date(h.at).toDateString()===new Date().toDateString()).reduce((n,h)=>n+(taskById(h.id)?.mins||0),0);shell(header('TODAY',t?'Seu próximo passo':'Trilha concluída',t?'Uma tarefa por vez. O próximo passo é liberado automaticamente.':'Todas as competências disponíveis foram concluídas.')+`<section class="today-focus">${t?`<div class="focus-label">${esc(p?.name||'Trilha')}</div><h2>${esc(t.name)}</h2><div class="focus-meta">${t.mins} min · etapa ${currentStage(t)+1}/${stagesFor(t).length} · ${taskPct(t)}% validado</div>${bar(taskPct(t))}<div class="focus-actions"><button class="primary" data-open="${t.id}">Continuar →</button><span>${overall()}% da carreira validada</span></div>`:'<h2>Nenhuma competência pendente e desbloqueada.</h2>'}</section><section class="today-grid"><div class="panel"><div class="panel-head"><div><h3>Depois disso</h3><small>próximos itens</small></div></div>${up.filter(x=>x.id!==t?.id).map(taskRow).join('')||'<div class="empty">Conclua o passo atual para liberar o próximo.</div>'}</div><div class="panel"><div class="panel-head"><div><h3>Seu progresso</h3><small>${completed().length} de ${allTasks().length}</small></div></div><div class="big-number">${overall()}%</div>${bar(overall())}<div class="mini-stats"><span>Estudo hoje <b>${tm} min</b></span><span>Inglês total <b>${state.english.minutes} min</b></span></div></div></section>`)}
function renderRoadmap(){shell(header('ROADMAP','Seu caminho','Somente a visão necessária; dependências permanecem internas.')+`<section class="roadmap-list">${data.phases.map(p=>{const s=phaseStats(p),active=p.tasks.some(t=>t.id===nextTask()?.id);return `<details class="phase-card" ${active?'open':''}><summary><div><b>${p.id} · ${esc(p.name)}</b><small>${s.done}/${s.total}</small></div><strong>${s.pct}%</strong></summary>${bar(s.pct)}<div class="phase-tasks">${p.tasks.map(taskRow).join('')}</div></details>`}).join('')}</section>`)}
function renderProgress(){shell(header('PROGRESS','Seu progresso','Só conta competência validada em todas as etapas.')+`<section class="progress-hero"><div class="big-number">${overall()}%</div>${bar(overall())}<span>${completed().length} de ${allTasks().length}</span></section><section class="domain-list">${data.phases.map(p=>{const s=phaseStats(p);return `<div class="domain"><div><span>${esc(p.name)}</span><b>${s.pct}%</b></div>${bar(s.pct)}</div>`}).join('')}</section><section class="panel english-panel"><div><h3>Inglês técnico</h3><p>${state.english.sessions} sessões · ${state.english.minutes} minutos</p></div><button class="primary" id="english60">+ 60 min</button></section>`)}
function renderCerts(){const groups=[['SC-900',['F12-01','F12-02']],['SC-300',['F12-03','F12-04']],['AZ-900',['F12-05']],['AWS Cloud Practitioner',['F12-06']]];shell(header('CERTIFICAÇÕES','Certificações','Validação complementar da trilha.')+`<section class="cert-grid">${groups.map(([n,ids])=>{const ts=ids.map(taskById).filter(Boolean),d=ts.filter(t=>done(t.id)).length,v=pct(d,ts.length);return `<article class="cert-card"><div class="cert-top"><span>${esc(n)}</span><b>${v}%</b></div>${bar(v)}<div class="cert-tasks">${ts.map(taskRow).join('')}</div></article>`}).join('')}</section>`)}
function renderLabs(){shell(header('LABS','Laboratórios','Laboratórios existentes viram evidência quando a competência correspondente chegar ao Today.')+`<section class="content-grid"><div class="panel"><h3>Existentes</h3><div class="evidence"><b>Cloud Security</b><span>Azure · Entra ID · RBAC · VNet · NSG · VM</span></div><div class="evidence"><b>On-Premises</b><span>AD · DNS · DHCP · GPO · WSUS · Wazuh · Suricata</span></div></div><div class="panel"><h3>Próximos</h3>${['Hybrid Identity','Enterprise SSO','PIM + Governance','Graph Automation','Entra → AWS Federation','IAM Architecture'].map(x=>`<div class="evidence"><b>${x}</b><small>liberado conforme dependências</small></div>`).join('')}</div></section>`)}
function renderSettings(){shell(header('CONFIG','Configurações','Backup e rotina.')+`<section class="panel settings"><div class="setting"><span>Objetivo</span><b>${esc(data.career.target)}</b></div><div class="setting"><span>Rotina</span><b>2h estudo + 1h inglês</b></div><div class="actions"><button class="secondary" id="export">Exportar progresso</button><button class="secondary" id="import">Importar</button><button class="danger" id="reset">Resetar</button><input id="file" type="file" accept="application/json" hidden></div></section>`)}
function taskDetail(id){const t=taskById(id);if(!t)return;const deps=(t.pre||[]).map(taskById).filter(Boolean),st=stagesFor(t);document.getElementById('modal').classList.remove('hidden');document.getElementById('modalBody').innerHTML=`<button class="close" data-close>×</button><div class="eyebrow">${esc(t.type)}</div><h2>${esc(t.name)}</h2><p class="muted">${t.mins} min · ${ready(t)?'disponível':'bloqueado'} · ${taskPct(t)}% validado</p>${bar(taskPct(t))}<div class="detail-steps">${st.map((label,i)=>`<button class="stage ${stageDone(t.id,i)?'complete':''}" data-stage="${t.id}" data-index="${i}" ${!ready(t)&&!done(t.id)?'disabled':''}><b>${stageDone(t.id,i)?'✓ ':''}${label}</b><small>${i===0?'Aprenda o conceito':i===1?'Execute ou aplique':i===2?'Teste, explique ou investigue':'Registre evidência e valide'}</small></button>`).join('')}</div>${deps.length?`<h3>Pré-requisitos</h3>${deps.map(d=>`<div class="dependency ${done(d.id)?'complete':''}">${done(d.id)?'✓':'○'} ${esc(d.name)}</div>`).join('')}`:''}<p class="muted">Marque cada etapa somente quando conseguir executá-la de verdade. Todas concluídas = competência concluída.</p>`}
function reset(){if(confirm('Resetar todo o progresso?')){state=blankState();save()}}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>render(b.dataset.view));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>taskDetail(b.dataset.open));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById('modal').classList.add('hidden'));document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>completeStage(b.dataset.stage,Number(b.dataset.index)));const m=document.getElementById('modal');if(m)m.onclick=e=>{if(e.target===m)m.classList.add('hidden')};const e=document.getElementById('english60');if(e)e.onclick=()=>{state.english.minutes+=60;state.english.sessions++;save()};const ex=document.getElementById('export');if(ex)ex.onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='iam-career-progress.json';a.click()};const im=document.getElementById('import');if(im)im.onclick=()=>document.getElementById('file').click();const f=document.getElementById('file');if(f)f.onchange=async()=>{try{state=JSON.parse(await f.files[0].text());save()}catch{alert('Arquivo inválido')}};const r=document.getElementById('reset');if(r)r.onclick=reset}
function render(view=currentView()){localStorage.setItem('iam-view',view);({today:renderToday,roadmap:renderRoadmap,progress:renderProgress,certs:renderCerts,labs:renderLabs,settings:renderSettings}[view]||renderToday)();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));bind()}render();
