(function(){
'use strict';
var KEY='iam-career-hub-state-v9', TASK_KEY='iam-hub-individual-tasks-v10';
var data=window.ROADMAP||{career:{target:'IAM Analyst / IAM Engineer'},phases:[]};
var learning=window.LEARNING||{}, resources=window.RESOURCES||{}, certs=window.CERTIFICATIONS||{};
var app=document.getElementById('app');
function fresh(){return {stageDone:{},done:{},evidence:{},english:{minutes:0,sessions:0},history:[],activityDone:{},started:new Date().toISOString()};}
function load(){var s=fresh();try{s=Object.assign(s,JSON.parse(localStorage.getItem(KEY)||'{}')||{});}catch(e){};s.stageDone=s.stageDone||{};s.done=s.done||{};s.evidence=s.evidence||{};s.english=s.english||{minutes:0,sessions:0};s.history=s.history||[];s.activityDone=s.activityDone||{};migrate(s);return s;}
function migrate(s){try{var old=JSON.parse(localStorage.getItem(TASK_KEY)||'{}')||{};Object.keys(old).forEach(function(k){if(old[k]===true&&!s.activityDone[k])s.activityDone[k]=true;});}catch(e){};return s;}
var state=load();
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function allTasks(){var a=[];(data.phases||[]).forEach(function(p){(p.tasks||[]).forEach(function(t){a.push({id:t.id,name:t.name,type:t.type||'knowledge',mins:t.mins||60,pre:t.pre||[],phaseId:p.id,phase:p.name,goal:t.goal||''});});});return a;}
function getTask(id){var a=allTasks();for(var i=0;i<a.length;i++)if(a[i].id===id)return a[i];return null;}
function stages(t){if(t.type==='lab')return ['Estudar','Executar','Troubleshoot','Evidenciar'];if(t.type==='validate')return ['Resolver cenário','Explicar sem consulta','Registrar validação'];return ['Estudar','Praticar','Recapitular','Validar'];}
function detail(t){var l=learning.enrich?learning.enrich(t):{};return {goal:l.goal||'Dominar a competência.',study:l.study||['Estudar documentação oficial.'],practice:l.practice||['Executar a prática.'],validate:l.validate||['Explicar sem consulta e resolver um cenário.'],evidence:l.evidence||'Registrar evidência objetiva.'};}
function lens(t){if(t.type==='lab')return [1,1,1,1];if(t.type==='validate')return [1,1,1];var l=detail(t);return [l.study.length,l.practice.length,4,l.validate.length];}
function k(id,s,n){return id+'|'+s+'|'+n;}
function activity(id,s,n){return state.activityDone[k(id,s,n)]===true;}
function stageComplete(id,s){var t=getTask(id);if(!t)return false;var len=lens(t)[s]||0;if(!len)return false;for(var n=0;n<len;n++)if(!activity(id,s,n))return false;return true;}
function syncTask(id){var t=getTask(id),ls=lens(t),ok=true;for(var s=0;s<ls.length;s++)if(!stageComplete(id,s)){ok=false;break;}state.stageDone[id]=ls.map(function(_,s){return stageComplete(id,s);});if(ok){if(!state.done[id])state.history.push({id:id,at:new Date().toISOString()});state.done[id]={at:(state.done[id]&&state.done[id].at)||new Date().toISOString(),evidence:state.evidence[id]||''};}else delete state.done[id];}
function ready(t){for(var i=0;i<t.pre.length;i++)if(!state.done[t.pre[i]])return false;return true;}
function pct(a,b){return b?Math.round(a*100/b):0;}
function taskPct(t){var ls=lens(t),n=0,total=0;ls.forEach(function(c,s){total+=c;for(var i=0;i<c;i++)if(activity(t.id,s,i))n++;});return pct(n,total);}
function overall(){var a=allTasks(),n=0;for(var i=0;i<a.length;i++)if(state.done[a[i].id])n++;return pct(n,a.length);}
function nextTask(){var a=allTasks();for(var i=0;i<a.length;i++)if(!state.done[a[i].id]&&ready(a[i]))return a[i];return null;}
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function bar(v){return '<div class="bar"><i style="width:'+v+'%"></i></div>';}
function nav(){return '<nav>'+[['today','Today'],['roadmap','Roadmap'],['progress','Progress'],['certs','Certificações'],['labs','Labs'],['settings','Config']].map(function(x){return '<button class="nav-btn" data-view="'+x[0]+'">'+x[1]+'</button>';}).join('')+'</nav>';}
function shell(content){app.innerHTML='<div class="app-shell"><aside class="sidebar"><div class="brand"><strong>IAM</strong><span>CAREER HUB</span></div><div class="career-chip"><span>Objetivo</span><b>'+esc(data.career.target)+'</b><small>Cloud IAM</small></div>'+nav()+'<div class="sidebar-foot"><span>3h estudo</span><span>1h inglês</span></div></aside><main>'+content+'</main></div>';}
function header(k,t,s){return '<header class="top"><div><div class="eyebrow">'+esc(k)+'</div><h1>'+esc(t)+'</h1>'+(s?'<p>'+esc(s)+'</p>':'')+'</div><time>'+new Date().toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'})+'</time></header>';}
function taskRow(t){return '<div class="task '+(state.done[t.id]?'done':'')+'"><div><b>'+(state.done[t.id]?'✓ ':'')+esc(t.name)+'</b><small>'+t.mins+' min · '+(state.done[t.id]?'concluído':ready(t)?taskPct(t)+'%':'bloqueado')+'</small></div><button class="icon-btn" data-page-task="'+esc(t.id)+'">Abrir</button></div>';}
function renderToday(){state=load();var t=nextTask(),next=null,a=allTasks();if(t){var ix=a.findIndex(function(x){return x.id===t.id;});for(var i=ix+1;i<a.length;i++)if(!state.done[a[i].id]&&ready(a[i])){next=a[i];break;}}var focus=t?'<div class="today-focus"><span class="focus-label">'+esc(t.phase)+'</span><h2>'+esc(t.name)+'</h2><p>'+t.mins+' min · '+taskPct(t)+'% concluído</p><button class="primary" data-page-task="'+esc(t.id)+'">Continuar →</button></div>':'<div class="today-focus"><h2>Trilha concluída</h2><p>Não há competência disponível.</p></div>';var after=next?'<section class="today-next"><span>PRÓXIMO</span><b>'+esc(next.name)+'</b></section>':'';shell(header('TODAY',t?'Faça agora':'Tudo concluído',t?'Uma competência por vez. Sem excesso de informação.':'Revise seu portfólio e avance para a próxima meta.')+focus+after+'<section class="today-routine"><span>3h conteúdo</span><span>1h inglês</span></section>');}
function renderRoadmap(){state=load();var h='';(data.phases||[]).forEach(function(p){var d=0;p.tasks.forEach(function(t){if(state.done[t.id])d++;});var active=nextTask();h+='<details class="phase-card" '+(active&&active.phaseId===p.id?'open':'')+'><summary><div><b>'+esc(p.id)+' · '+esc(p.name)+'</b><small>'+d+'/'+p.tasks.length+'</small></div><strong>'+pct(d,p.tasks.length)+'%</strong></summary>'+bar(pct(d,p.tasks.length))+'<div class="phase-tasks">'+p.tasks.map(taskRow).join('')+'</div></details>';});shell(header('ROADMAP','Seu caminho','Básico → intermediário → avançado.')+'<section class="roadmap-list">'+h+'</section>');}
function renderProgress(){state=load();var a=allTasks(),domains='';(data.phases||[]).forEach(function(p){var d=p.tasks.filter(function(t){return state.done[t.id];}).length;domains+='<div class="domain"><div><span>'+esc(p.name)+'</span><b>'+pct(d,p.tasks.length)+'%</b></div>'+bar(pct(d,p.tasks.length))+'</div>';});shell(header('PROGRESS','Progresso','Somente o que foi validado conta.')+'<section class="progress-hero"><div class="big-number">'+overall()+'%</div>'+bar(overall())+'<span>'+a.filter(function(t){return state.done[t.id];}).length+' de '+a.length+' competências</span></section><section class="domain-list">'+domains+'</section><section class="panel english-panel"><div><h3>Inglês técnico</h3><p>'+state.english.sessions+' sessões · '+state.english.minutes+' min</p></div><button class="primary" id="english60">+ 60 min</button></section>');}
function certLevel(c){if(c.level==='Fundamental'||c.level==='Foundational')return 'Básico';if(c.level==='Associate'||c.level==='Professional')return 'Intermediário';return 'Avançado';}
function renderCerts(){state=load();var all=certs.tracks||[];var h='<section class="cert-path panel"><div class="eyebrow">ORDEM</div><h2>SC-900 → AZ-900 → SC-300 → AZ-104 conforme vaga → AWS SAA → AWS Security</h2><p>Certificação acompanha a prática; não substitui laboratório.</p></section>';['Básico','Intermediário','Avançado'].forEach(function(level){var list=all.filter(function(c){return certLevel(c)===level;});if(!list.length)return;h+='<section class="cert-section"><h2>'+level+'</h2><div class="cert-grid">'+list.map(function(c){return '<article class="cert-card"><h3>'+esc(c.name)+'</h3><small>'+esc(c.provider||'')+'</small><p>'+esc(c.why||'')+'</p></article>';}).join('')+'</div></section>';});shell(header('CERTIFICAÇÕES','Trilha de certificações','Prioridade para IAM/Cloud.')+h);}
function renderLabs(){shell(header('LABS','Laboratórios','Produza evidência, não apenas screenshots.')+'<section class="content-grid"><div class="panel"><h3>Existentes</h3><div class="evidence"><b>Cloud Security</b><span>Azure · Entra ID · RBAC · VNet · NSG · VM</span></div><div class="evidence"><b>On-Premises</b><span>AD · DNS · DHCP · GPO · Wazuh · Suricata</span></div></div><div class="panel"><h3>Próximos</h3>'+['Hybrid Identity','Enterprise SSO','PIM + Governance','Graph Automation','Entra → AWS Federation','IAM Architecture'].map(function(x){return '<div class="evidence"><b>'+x+'</b></div>';}).join('')+'</div></section>');}
function renderSettings(){shell(header('CONFIG','Configurações','Rotina e dados.')+'<section class="panel settings"><div class="setting"><span>Objetivo</span><b>'+esc(data.career.target)+'</b></div><div class="setting"><span>Rotina</span><b>3h conteúdo + 1h inglês</b></div><div class="actions"><button class="secondary" id="export">Exportar</button><button class="secondary" id="import">Importar</button><button class="danger" id="reset">Resetar</button><input id="file" type="file" accept="application/json" hidden></div></section>');}
function renderTaskPage(id){state=load();var t=getTask(id);if(!t){render('today');return;}var l=detail(t),ls=lens(t),html='<div class="task-page"><div class="back-row"><button class="secondary" id="backTask">← Today</button><span>'+esc(t.phase)+'</span></div><div class="task-page-head"><div class="eyebrow">'+esc(t.id)+'</div><h1>'+esc(t.name)+'</h1><p>'+t.mins+' min · '+taskPct(t)+'% · '+(ready(t)?'disponível':'bloqueada')+'</p></div><div class="task-page-grid"><article class="panel learning-panel"><section><h2>Objetivo</h2><p>'+esc(l.goal)+'</p></section>'+section('Estudar',l.study,t,0)+section('Praticar',l.practice,t,1)+section('Recapitular',['Explique os conceitos sem consultar.','Reconstrua o fluxo ou arquitetura de memória.','Liste os erros encontrados e como os corrigiu.','Diga onde esta competência é usada em produção.'],t,2)+section('Validar',l.validate,t,3)+'<section><h2>Evidência</h2><p>'+esc(l.evidence)+'</p></section></article><aside class="task-page-side"><div class="panel"><h2>Etapas</h2><div class="page-stages">'+stages(t).map(function(s,i){return '<div class="stage '+(stageComplete(t.id,i)?'complete':'')+'"><b>'+(stageComplete(t.id,i)?'✓ ':'')+esc(s)+'</b><small>'+pct(countDone(t,i),ls[i])+'%</small></div>';}).join('')+'</div></div><div class="panel"><label class="evidence-input"><span>Nota / evidência</span><textarea id="evidenceText" rows="6" placeholder="Comando, configuração, resultado ou link.">'+esc(state.evidence[t.id]||'')+'</textarea><button class="secondary" id="saveEvidence">Salvar</button></label></div></aside></div></div>';shell(html);bindTaskPage(id);}
function countDone(id,s){var t=getTask(id),n=0,c=(lens(t)[s]||0);for(var i=0;i<c;i++)if(activity(id,s,i))n++;return n;}
function section(title,items,t,s){return '<section><h2>'+title+'</h2>'+items.map(function(x,i){var d=activity(t.id,s,i);return '<p class="detail-line '+(d?'individual-task-done':'')+'" data-activity="'+esc(k(t.id,s,i))+'"><span class="check">'+(d?'✓':'○')+'</span>'+esc(x)+'</p>';}).join('')+'</section>';}
function bindTaskPage(id){var b=document.getElementById('backTask');if(b)b.onclick=function(){location.hash='';render('today');};document.querySelectorAll('[data-activity]').forEach(function(x){x.onclick=function(){var key=x.getAttribute('data-activity');state=load();state.activityDone[key]=!state.activityDone[key];var parts=key.split('|');syncTask(parts[0]);save();renderTaskPage(id);};});var s=document.getElementById('saveEvidence');if(s)s.onclick=function(){state=load();state.evidence[id]=document.getElementById('evidenceText').value;save();renderTaskPage(id);};}
function bind(){document.querySelectorAll('[data-view]').forEach(function(x){x.onclick=function(){location.hash='';localStorage.setItem('iam-view',x.getAttribute('data-view'));render(x.getAttribute('data-view'));};});document.querySelectorAll('[data-page-task]').forEach(function(x){x.onclick=function(){location.hash='task/'+encodeURIComponent(x.getAttribute('data-page-task'));renderTaskPage(x.getAttribute('data-page-task'));};});var e=document.getElementById('english60');if(e)e.onclick=function(){state=load();state.english.minutes+=60;state.english.sessions++;save();render('progress');};var r=document.getElementById('reset');if(r)r.onclick=function(){if(confirm('Resetar todo o progresso?')){state=fresh();save();render('today');}};var ex=document.getElementById('export');if(ex)ex.onclick=function(){state=load();var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='iam-career-progress.json';a.click();};var im=document.getElementById('import');if(im)im.onclick=function(){document.getElementById('file').click();};var f=document.getElementById('file');if(f)f.onchange=function(){var reader=new FileReader();reader.onload=function(){try{state=JSON.parse(reader.result);save();render('today');}catch(err){alert('Arquivo inválido.');}};reader.readAsText(f.files[0]);};}
function render(v){state=load();var hash=location.hash.replace(/^#/,'');if(hash.indexOf('task/')===0){renderTaskPage(decodeURIComponent(hash.slice(5)));return;}if(v==='roadmap')renderRoadmap();else if(v==='progress')renderProgress();else if(v==='certs')renderCerts();else if(v==='labs')renderLabs();else if(v==='settings')renderSettings();else renderToday();bind();document.querySelectorAll('[data-view]').forEach(function(n){if(n.getAttribute('data-view')===v)n.classList.add('active');});}
window.addEventListener('hashchange',function(){var h=location.hash.replace(/^#/,'');if(h.indexOf('task/')===0)renderTaskPage(decodeURIComponent(h.slice(5)));else render(localStorage.getItem('iam-view')||'today');});
window.addEventListener('roadmap:state-changed',function(){render(localStorage.getItem('iam-view')||'today');});
render(localStorage.getItem('iam-view')||'today');
})();
