const KEY='iam-career-hub-state-v2';
const data=window.ROADMAP;
const blankState=()=>({done:{},english:{minutes:0,sessions:0},studyMinutes:0,sessions:0,started:new Date().toISOString(),history:[],notes:{}});
let state=JSON.parse(localStorage.getItem(KEY)||'null')||blankState();
const app=document.getElementById('app');
const allTasks=()=>data.phases.flatMap(p=>p.tasks.map(t=>({...t,phaseId:p.id,phase:p.name,goal:p.goal})));
const taskById=id=>allTasks().find(t=>t.id===id);
const isDone=id=>!!state.done[id];
const completed=()=>allTasks().filter(t=>isDone(t.id));
const pct=(a,b)=>b?Math.round(a/b*100):0;
const ready=t=>(t.pre||[]).every(isDone);
const phaseStats=p=>{const total=p.tasks.length,done=p.tasks.filter(t=>isDone(t.id)).length;return{total,done,pct:pct(done,total)}};
const overall=()=>pct(completed().length,allTasks().length);
function nextTask(){const pending=allTasks().filter(t=>!isDone(t.id)&&ready(t));return pending.find(t=>t.type==='study')||pending.find(t=>t.type==='lab')||pending[0]||null}
function upcoming(){return allTasks().filter(t=>!isDone(t.id)&&ready(t)).slice(0,7)}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render(currentView())}
function toggle(id){if(!taskById(id))return;if(isDone(id))delete state.done[id];else{state.done[id]={at:new Date().toISOString()};state.history.push({id,at:new Date().toISOString()})}save()}
function currentView(){return localStorage.getItem('iam-view')||'today'}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function phaseOf(t){return data.phases.find(p=>p.id===t.phaseId)}
function taskCard(t){const d=isDone(t.id),locked=!d&&!ready(t);return `<article class="task ${d?'done':''} ${locked?'locked':''}"><div class="task-main"><div class="task-title">${d?'✓ ':''}${escapeHtml(t.name)}</div><div class="task-meta"><span>${escapeHtml(t.type)}</span><span>${t.mins} min</span>${locked?'<span>bloqueado</span>':''}</div></div><div class="task-actions"><button class="icon-btn" data-open="${t.id}" aria-label="Detalhes">›</button>${!locked?`<button class="check-btn ${d?'checked':''}" data-check="${t.id}" aria-label="${d?'Desmarcar':'Concluir'}">${d?'✓':'○'}</button>`:''}</div></article>`}
function header(kicker,title,sub=''){return `<header class="top"><div><div class="eyebrow">${kicker}</div><h1>${escapeHtml(title)}</h1><p>${escapeHtml(sub)}</p></div><time>${new Date().toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'})}</time></header>`}
function shell(content){app.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><strong>IAM</strong><span>CAREER HUB</span></div><div class="career-chip"><span>Objetivo</span><b>IAM Engineer</b><small>Cloud IAM · Identity</small></div><nav>${[['today','Today','◷'],['roadmap','Roadmap','◇'],['progress','Progress','◌'],['certs','Certifications','□'],['labs','Labs & Evidence','⌁'],['settings','Settings','⚙']].map(x=>`<button class="nav-btn" data-view="${x[0]}"><i>${x[2]}</i>${x[1]}</button>`).join('')}</nav><div class="sidebar-foot"><span>2h estudo</span><span>1h inglês</span></div></aside><main>${content}</main></div><div id="modal" class="modal hidden"><div class="modal-card" id="modalBody"></div></div>`}
function metric(label,value,sub=''){return `<div class="metric-card"><span>${label}</span><strong>${value}</strong><small>${sub}</small></div>`}
function renderToday(){const t=nextTask(),phase=t?phaseOf(t):null,up=upcoming();const dayStudy=Math.min(120,Math.max(0,state.studyMinutes%121));shell(header('TODAY',t?`Fase ${phase.id.replace('F','')} · ${phase.name}`:'Trilha atual concluída',t?phase.goal:'Todas as competências disponíveis foram concluídas.')+`<section class="hero-grid"><div class="hero-card"><div class="eyebrow">próximo passo</div>${t?`<h2>${escapeHtml(t.name)}</h2><div class="task-meta"><span>${t.type}</span><span>${t.mins} min</span></div><div class="hero-progress"><i style="width:${overall()}%"></i></div><div class="hero-footer"><span><b>${overall()}%</b> da trilha</span><button class="primary" data-open="${t.id}">Continuar →</button></div>`:'<h2>Você terminou as competências desbloqueadas.</h2>'}</div><div class="stats">${metric('Progresso',overall()+'%',`${completed().length}/${allTasks().length} competências`)}${metric('Estudo hoje',dayStudy+' min','meta: 120 min')}${metric('Inglês',state.english.minutes+' min','registrado')}</div></section><section class="content-grid"><div class="panel"><div class="panel-head"><div><h3>Próximos passos</h3><small>ordem calculada pelas dependências</small></div></div>${up.map(taskCard).join('')||'<div class="empty">Nenhuma competência desbloqueada.</div>'}</div><div class="panel"><div class="panel-head"><div><h3>Seu caminho</h3><small>progresso por fase</small></div><button class="text-btn" data-view="roadmap">ver tudo</button></div>${data.phases.slice(0,8).map(p=>{const s=phaseStats(p);return `<div class="phase-row"><div><span>${escapeHtml(p.name)}</span><b>${s.pct}%</b></div><div class="bar"><i style="width:${s.pct}%"></i></div></div>`}).join('')}</div></section>`);}
function renderRoadmap(){shell(header('ROADMAP','Sua trajetória','A próxima etapa é calculada automaticamente. Conhecimentos prévios permanecem pendentes até sua validação.')+`<section class="toolbar"><input id="search" placeholder="Pesquisar competência, protocolo, ferramenta..." autocomplete="off"><span>${completed().length}/${allTasks().length} concluídas</span></section><section id="roadmap-list" class="roadmap-list">${data.phases.map(p=>{const s=phaseStats(p);return `<details class="phase-card" ${p.tasks.some(t=>t.id===nextTask()?.id)?'open':''}><summary><div><b>${p.id} · ${escapeHtml(p.name)}</b><small>${escapeHtml(p.goal)}</small></div><strong>${s.pct}%</strong></summary><div class="phase-progress"><i style="width:${s.pct}%"></i></div><div class="phase-tasks">${p.tasks.map(taskCard).join('')}</div></details>`}).join('')}</section>`)}
function renderProgress(){shell(header('PROGRESS','Evolução','O progresso é consequência das competências que você realmente validou.')+`<section class="stats-grid">${metric('Geral',overall()+'%',`${completed().length} concluídas`)}${metric('Restantes',(allTasks().length-completed().length),'competências')}${metric('Inglês',state.english.sessions,'sessões')}${metric('Histórico',state.history.length,'ações registradas')}</section><section class="content-grid"><div class="panel"><div class="panel-head"><div><h3>Domínios</h3><small>competências concluídas / total</small></div></div>${data.phases.map(p=>{const s=phaseStats(p);return `<div class="domain"><div><span>${p.id} · ${escapeHtml(p.name)}</span><b>${s.pct}%</b></div><div class="bar"><i style="width:${s.pct}%"></i></div></div>`}).join('')}</div><div class="panel"><div class="panel-head"><div><h3>Atividade recente</h3><small>últimas validações</small></div></div>${state.history.slice(-10).reverse().map(h=>{const t=taskById(h.id);return `<div class="history"><span>✓</span><div><b>${escapeHtml(t?.name||h.id)}</b><small>${new Date(h.at).toLocaleString('pt-BR')}</small></div></div>`}).join('')||'<div class="empty">Nenhuma competência concluída.</div>'}</div></section><section class="panel english-panel"><div><h3>Inglês técnico</h3><p>Registre sua sessão diária de 60 minutos para acompanhar consistência.</p></div><button class="primary" id="english60">+ 60 min</button></section>`)}
function renderCerts(){const map=[['SC-900',['F12-01','F12-02']],['SC-300',['F12-03','F12-04']],['AZ-900',['F12-05']],['AWS Cloud Practitioner',['F12-06']]];shell(header('CERTIFICATIONS','Certificações','Checkpoints de conhecimento dentro da trilha, sem substituir prática.')+`<section class="cert-grid">${map.map(([name,ids])=>{const ts=ids.map(taskById).filter(Boolean),d=ts.filter(t=>isDone(t.id)).length;return `<article class="cert-card"><div class="cert-top"><span>certificação</span><b>${pct(d,ts.length)}%</b></div><h2>${name}</h2><div class="bar"><i style="width:${pct(d,ts.length)}%"></i></div>${ts.map(taskCard).join('')}</article>`}).join('')}</section>`)}
function renderLabs(){shell(header('LABS & EVIDENCE','Laboratórios e evidências','Seu laboratório existente é reaproveitado, mas a competência só é concluída após revalidação.')+`<section class="content-grid"><div class="panel"><h3>Base existente</h3><div class="evidence"><b>Laboratório Cloud Security</b><span>Azure · Entra ID · RBAC · VNet · NSG · VM · hardening</span><small>Status: revisar e revalidar</small></div><div class="evidence"><b>Laboratório On-Premises</b><span>AD · DNS · DHCP · GPO · WSUS · Wazuh · Suricata</span><small>Status: revisar e revalidar</small></div></div><div class="panel"><h3>Projetos de domínio</h3>${['Hybrid Identity Lab','Enterprise SSO Lab','PIM + Governance Lab','Graph IAM Automation','Entra → AWS Federation','IAM Architecture Final Project'].map(x=>`<div class="evidence"><b>${x}</b><small>desbloqueado conforme competências</small></div>`).join('')}</div></section>`)}
function renderSettings(){shell(header('SETTINGS','Controle do Hub','Dados de progresso são armazenados localmente neste navegador.')+`<section class="content-grid"><div class="panel"><h3>Objetivo</h3><div class="setting"><span>Cargo-alvo</span><b>${escapeHtml(data.career.target)}</b></div><div class="setting"><span>Foco</span><b>${escapeHtml(data.career.focus)}</b></div><div class="setting"><span>Rotina</span><b>2h estudo + 1h inglês</b></div></div><div class="panel"><h3>Dados</h3><p>Use exportação para manter backup antes de trocar de navegador ou dispositivo.</p><div class="actions"><button class="secondary" id="export">Exportar progresso</button><button class="secondary" id="import">Importar progresso</button><button class="danger" id="reset">Resetar progresso</button><input id="file" type="file" accept="application/json" hidden></div></div></section>`)}
function taskDetail(id){const t=taskById(id);if(!t)return;const deps=(t.pre||[]).map(taskById).filter(Boolean),p=phaseOf(t);const d=isDone(id);document.getElementById('modal').classList.remove('hidden');document.getElementById('modalBody').innerHTML=`<button class="close" data-close>×</button><div class="eyebrow">${escapeHtml(p?.name||'Competência')}</div><h2>${escapeHtml(t.name)}</h2><div class="task-meta"><span>${t.type}</span><span>${t.mins} min</span><span>${ready(t)?'desbloqueado':'bloqueado'}</span></div><div class="detail-steps"><div><b>01 · Estudar</b><p>Use documentação oficial, curso ou material técnico. Registre o que precisa saber, não apenas o que leu.</p></div><div><b>02 · Praticar</b><p>Execute o conceito no laboratório e provoque pelo menos um cenário de troubleshooting quando aplicável.</p></div><div><b>03 · Validar</b><p>Explique sem consulta e resolva um cenário prático relacionado à competência.</p></div><div><b>04 · Evidenciar</b><p>Guarde comandos, arquitetura, logs, screenshots, resultado ou documentação no portfólio quando fizer sentido.</p></div></div><h3>Pré-requisitos</h3>${deps.length?deps.map(x=>`<div class="dependency ${isDone(x.id)?'complete':''}">${isDone(x.id)?'✓':'○'} ${escapeHtml(x.name)}</div>`).join(''):'<p class="muted">Nenhum.</p>'}<button class="primary full" data-check="${t.id}" ${!ready(t)&&!d?'disabled':''}>${d?'Marcar como pendente':'Concluir competência'}</button>`}
function reset(){if(confirm('Resetar todo o progresso local?')){state=blankState();save()}}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>render(b.dataset.view));document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>toggle(b.dataset.check));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>taskDetail(b.dataset.open));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById('modal').classList.add('hidden'));const modal=document.getElementById('modal');if(modal)modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')};const search=document.getElementById('search');if(search)search.oninput=()=>{const q=search.value.toLowerCase().trim();document.querySelectorAll('.phase-card').forEach(p=>p.style.display=p.innerText.toLowerCase().includes(q)?'block':'none')};const e=document.getElementById('english60');if(e)e.onclick=()=>{state.english.minutes+=60;state.english.sessions++;save()};const ex=document.getElementById('export');if(ex)ex.onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='iam-career-hub-progress.json';a.click()};const im=document.getElementById('import');if(im)im.onclick=()=>document.getElementById('file').click();const file=document.getElementById('file');if(file)file.onchange=async()=>{try{state=JSON.parse(await file.files[0].text());save()}catch{alert('Arquivo inválido')}};const r=document.getElementById('reset');if(r)r.onclick=reset}
function render(view=currentView()){localStorage.setItem('iam-view',view);({today:renderToday,roadmap:renderRoadmap,progress:renderProgress,certs:renderCerts,labs:renderLabs,settings:renderSettings}[view]||renderToday)();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));bind()}
render();
