(function(){
'use strict';
var KEY='iam-career-hub-state-v8';
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function state(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{};}catch(e){return {};}}
function done(s,id){return !!(s.done&&s.done[id]);}
function gateReady(c,s){var missing=[];(c.gate||[]).forEach(function(id){if(!done(s,id))missing.push(id);});(c.after||[]).forEach(function(id){var cert=(window.CERTIFICATIONS.tracks||[]).find(function(x){return x.id===id;});if(cert&&!(s.certifications&&s.certifications[id]))missing.push(cert.name);});return {ok:missing.length===0,missing:missing};}
function status(c,s){if(s.certifications&&s.certifications[c.id])return 'concluída';var g=gateReady(c,s);if(g.ok)return 'disponível';return (c.after||[]).some(function(id){var x=(window.CERTIFICATIONS.tracks||[]).find(function(v){return v.id===id;});return x&&!(s.certifications&&s.certifications[id]);})?'aguardando anterior':'em preparação';}
function pct(c,s){var n=0,total=(c.gate||[]).length;(c.gate||[]).forEach(function(id){if(done(s,id))n++;});return total?Math.round(n*100/total):100;}
function render(){var root=document.querySelector('.cert-grid'),all=window.CERTIFICATIONS&&window.CERTIFICATIONS.tracks;if(!root||!all)return;var s=state(),html='';all.forEach(function(c){var st=status(c,s),g=gateReady(c,s),p=pct(c,s),cl=st==='concluída'?'done':st==='disponível'?'ready':'locked';html+='<article class="cert-card '+cl+'"><div class="cert-top"><span>'+esc(c.name)+'</span><b>'+esc(st)+'</b></div><p class="muted">'+esc(c.provider)+' · '+esc(c.level)+' · '+esc(c.priority)+'</p><p>'+esc(c.why)+'</p><div class="cert-gate"><small>Competências: '+p+'%</small><div class="bar"><i style="width:'+p+'%"></i></div></div>'+(g.ok&&st!=='concluída'?'<button class="primary cert-complete-v2" data-cert="'+esc(c.id)+'">Marcar certificação concluída</button>':'')+(st==='concluída'?'<small class="cert-ok">✓ registrada no seu histórico</small>':'')+(g.missing.length&&!g.ok?'<small class="muted">Bloqueada por: '+esc(g.missing.slice(0,4).join(', '))+(g.missing.length>4?'…':'')+'</small>':'')+'</article>';});root.innerHTML=html;root.querySelectorAll('.cert-complete-v2').forEach(function(b){b.onclick=function(){var x=state();if(!x.certifications)x.certifications={};x.certifications[b.getAttribute('data-cert')]={at:new Date().toISOString()};localStorage.setItem(KEY,JSON.stringify(x));render();};});}
function watch(){setInterval(function(){var h=document.querySelector('.top h1');if(h&&h.textContent==='Certificações'){var root=document.querySelector('.cert-grid');if(root&&root.children.length!==(window.CERTIFICATIONS.tracks||[]).length)render();}},500);setTimeout(render,100);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();
