const DOMAINS=[
{id:'fundamentals',name:'Fundamentos de TI',icon:'◈',color:'slate',topics:['Hardware e arquitetura','Windows e Linux','Processos e memória','Sistemas de arquivos e permissões','Virtualização','Git e controle de versão','PowerShell / Bash','Python / APIs','Fundamentos de Segurança','CIA Triad e gestão de risco']},
{id:'network',name:'Redes & Protocolos',icon:'⌁',color:'orange',topics:['OSI / TCP-IP','IPv4 / IPv6','Subnetting','DNS / DHCP','HTTP / HTTPS','Routing / Switching','VLAN / VPN','Firewall / NGFW','Wireshark / tcpdump','IDS / IPS / Zeek']},
{id:'cloud',name:'Cloud & Infraestrutura',icon:'☁',color:'blue',topics:['Cloud Fundamentals','AWS Core Services','Azure Core Services','Compute / Storage / Networking','Cloud IAM','Logging e Monitoring','Governance e Cost','Hybrid Infrastructure','Containers','Terraform / IaC']},
{id:'iam',name:'IAM',icon:'◉',color:'violet',topics:['Authentication','Authorization','RBAC / ABAC','MFA / Passwordless','SSO / Federation','SAML / OAuth / OIDC','Microsoft Entra ID','Active Directory','Hybrid Identity','Workload / Machine Identity','Identity Security'],certs:['SC-300','Okta Certified Professional']},
{id:'iga',name:'IGA',icon:'◇',color:'purple',topics:['Identity Lifecycle','Joiner / Mover / Leaver','Provisioning','Access Requests','Access Reviews','Access Certification','Entitlement Management','Segregation of Duties']},
{id:'pam',name:'PAM',icon:'▣',color:'red',topics:['Privileged Accounts','PIM','JIT / JEA','Credential Vaulting','Privileged Sessions','CyberArk','BeyondTrust']},
{id:'endpoint',name:'Endpoint & Device',icon:'▤',color:'cyan',topics:['Windows Security','Linux Security','Intune / MDM','Device Identity','Compliance','Endpoint Hardening','EDR / XDR','Defender for Endpoint']},
{id:'soc',name:'Security Operations',icon:'⌁',color:'amber',topics:['SOC Fundamentals','SIEM','Microsoft Sentinel','Splunk','KQL','Sigma','SOAR','EDR / XDR','Detection Engineering','Threat Hunting','MITRE ATT&CK','Incident Triage']},
{id:'ir',name:'Incident Response & Forensics',icon:'⚡',color:'rose',topics:['Incident Response Lifecycle','Triage','Containment','Eradication','Recovery','Windows / Linux Forensics','Disk / Memory Forensics','Timeline Analysis','Malware Analysis']},
{id:'vuln',name:'Vulnerability & Exposure',icon:'△',color:'yellow',topics:['Asset Inventory','Vulnerability Management','CVE / CVSS','Patch Management','Attack Surface','CIS Benchmarks','Hardening','Exposure Prioritization']},
{id:'appsec',name:'AppSec & DevSecOps',icon:'⌘',color:'green',topics:['Secure SDLC','OWASP Top 10','API Security','Authentication flaws','SAST / DAST','SCA','Secrets Scanning','CI/CD Security','SBOM','Supply Chain Security']},
{id:'data',name:'Data Security & Privacy',icon:'▦',color:'teal',topics:['Classification','Discovery','Encryption','DLP','Information Protection','Insider Risk','eDiscovery','Retention','LGPD / GDPR','Data Loss Prevention']},
{id:'crypto',name:'Cryptography & PKI',icon:'◇',color:'indigo',topics:['Hashing','Symmetric / Asymmetric Crypto','Digital Signatures','TLS','PKI','Certificates','HSM','Key Management','Secrets Management','Post-Quantum Readiness']},
{id:'grc',name:'GRC & Risk',icon:'◆',color:'gold',topics:['Governance','Risk Assessment','Risk Treatment','Security Controls','NIST CSF 2.0','NIST SP 800-53','CIS Controls','ISO 27001','Audit','LGPD / GDPR','Third-Party Risk','Security Metrics']},
{id:'architecture',name:'Security Architecture',icon:'⬡',color:'blue',topics:['Security Architecture','Zero Trust','Identity Architecture','Cloud Security Architecture','Hybrid Architecture','Network Security Architecture','Data Security Architecture','Threat Modeling','Security Strategy','Security Design Reviews']},
{id:'resilience',name:'Resiliência & Continuidade',icon:'◒',color:'green',topics:['Business Continuity','BIA','BCP','DRP','RTO / RPO','Backup','Disaster Recovery','Crisis Management']},
{id:'ai',name:'AI Security',icon:'✦',color:'pink',topics:['AI / ML Fundamentals','LLM Architecture','Prompt Injection','Data Poisoning','Model Security','AI Data Security','AI Threat Modeling','MITRE ATLAS','AI Governance','Agentic AI Security']},
{id:'offensive',name:'Offensive Security',icon:'⌖',color:'red',topics:['Reconnaissance','OSINT','Enumeration','Web Security','API Testing','AD Attacks','Network Testing','Exploitation','Privilege Escalation','Red Team','Reporting'],certs:['OSCP']}
];
const CERTS=[
{id:'cc',name:'CC',title:'Certified in Cybersecurity',domain:'fundamentals',provider:'ISC2',level:'Entry-level',type:'Certification'},
{id:'securityplus',name:'Security+',title:'CompTIA Security+',domain:'fundamentals',provider:'CompTIA',level:'Entry-level',type:'Certification'},
{id:'sc900',name:'SC-900',title:'Security, Compliance, and Identity Fundamentals',domain:'fundamentals',provider:'Microsoft',level:'Fundamental',type:'Certification'},
{id:'az900',name:'AZ-900',title:'Azure Fundamentals',domain:'cloud',provider:'Microsoft',level:'Fundamental',type:'Certification'},
{id:'awsccp',name:'AWS Cloud Practitioner',title:'AWS Certified Cloud Practitioner',domain:'cloud',provider:'AWS',level:'Foundational',type:'Certification'},
{id:'networkplus',name:'Network+',title:'CompTIA Network+',domain:'network',provider:'CompTIA',level:'Entry-level',type:'Certification'},
{id:'ccna',name:'CCNA',title:'Cisco Certified Network Associate',domain:'network',provider:'Cisco',level:'Associate',type:'Certification'},
{id:'az104',name:'AZ-104',title:'Azure Administrator Associate',domain:'cloud',provider:'Microsoft',level:'Intermediate',type:'Certification'},
{id:'awssaa',name:'AWS SAA',title:'AWS Certified Solutions Architect – Associate',domain:'cloud',provider:'AWS',level:'Associate',type:'Certification'},
{id:'sc300',name:'SC-300',title:'Identity and Access Administrator Associate',domain:'iam',provider:'Microsoft',level:'Intermediate',type:'Certification'},
{id:'md102',name:'MD-102',title:'Endpoint Administrator Associate',domain:'endpoint',provider:'Microsoft',level:'Intermediate',type:'Certification'},
{id:'sc200',name:'SC-200',title:'Security Operations Analyst Associate',domain:'soc',provider:'Microsoft',level:'Intermediate',type:'Certification'},
{id:'cysa',name:'CySA+',title:'CompTIA Cybersecurity Analyst',domain:'soc',provider:'CompTIA',level:'Intermediate',type:'Certification'},
{id:'btl1',name:'BTL1',title:'Blue Team Level 1',domain:'soc',provider:'Security Blue Team',level:'Practical',type:'Certification'},
{id:'sc400',name:'SC-400',title:'Information Protection and Compliance Administrator',domain:'data',provider:'Microsoft',level:'Intermediate',type:'Certification'},
{id:'awssec',name:'AWS Security Specialty',title:'AWS Certified Security – Specialty',domain:'cloud',provider:'AWS',level:'Specialty',type:'Certification'},
{id:'ccsp',name:'CCSP',title:'Certified Cloud Security Professional',domain:'cloud',provider:'ISC2',level:'Advanced',type:'Certification'},
{id:'cisa',name:'CISA',title:'Certified Information Systems Auditor',domain:'grc',provider:'ISACA',level:'Advanced',type:'Certification'},
{id:'cism',name:'CISM',title:'Certified Information Security Manager',domain:'grc',provider:'ISACA',level:'Advanced',type:'Certification'},
{id:'crisc',name:'CRISC',title:'Certified in Risk and Information Systems Control',domain:'grc',provider:'ISACA',level:'Advanced',type:'Certification'},
{id:'csslp',name:'CSSLP',title:'Certified Secure Software Lifecycle Professional',domain:'appsec',provider:'ISC2',level:'Advanced',type:'Certification'},
{id:'sc100',name:'SC-100',title:'Cybersecurity Architect Expert',domain:'architecture',provider:'Microsoft',level:'Expert',type:'Certification'},
{id:'okta',name:'Okta Certified Professional',title:'Okta Certified Professional',domain:'iam',provider:'Okta',level:'Professional',type:'Certification'},
{id:'sailpoint',name:'SailPoint Identity Security Professional',title:'Identity Security Professional',domain:'iga',provider:'SailPoint',level:'Knowledge Credential',type:'Credential'},
{id:'cyberark',name:'CyberArk Defender - PAM',title:'Defender - PAM',domain:'pam',provider:'CyberArk',level:'Intermediate / Advanced',type:'Certification'},
{id:'oscp',name:'OSCP',title:'Offensive Security Certified Professional',domain:'offensive',provider:'OffSec',level:'Advanced',type:'Certification'},
{id:'cissp',name:'CISSP',title:'Certified Information Systems Security Professional',domain:'architecture',provider:'ISC2',level:'Advanced',type:'Certification'},
{id:'gcih',name:'GCIH',title:'GIAC Certified Incident Handler',domain:'ir',provider:'GIAC',level:'Advanced',type:'Certification'}
];
const ROADMAP_META={start:{title:'Ponto de partida'}};window.DOMAINS=DOMAINS;window.CERTS=CERTS;window.ROADMAP_META=ROADMAP_META;
