param([Parameter(Position=0)][string]$Comando="agora")
$Root=Split-Path $PSScriptRoot -Parent
$EstadoPath=Join-Path $Root "docs\progresso\estado.json"
$PainelPath=Join-Path $Root "docs\progresso\painel.md"
$VerificarPath=Join-Path $Root "scripts\verificar-roadmap.ps1"
function Ler-Estado{if(!(Test-Path $EstadoPath)){throw "Estado nao encontrado: $EstadoPath"};Get-Content $EstadoPath -Raw -Encoding UTF8|ConvertFrom-Json}
function Salvar($e){$j=$e|ConvertTo-Json -Depth 10;[IO.File]::WriteAllText($EstadoPath,$j,(New-Object Text.UTF8Encoding($false)))}
function Atual($e){@($e.fases)|?{[int]$_.id -eq [int]$e.faseAtual}|select -First 1}
function Prox($e,$f){@($e.fases)|?{[int]$_.id -gt [int]$f.id}|sort id|select -First 1}
function Pct($f){$n=@($f.passos|?{$_.feito}).Count+$(if($f.testeConcluido){1}else{0});[math]::Round(($n/5)*100)}
function Painel($e){$f=Atual $e;$l=@("# Painel do MeuRoadmap","","## Fase atual","","**$($f.id.ToString('00')) - $($f.nome)**","","**Progresso:** $(Pct $f)%","","### Etapas","");foreach($p in @($f.passos)){$m=if($p.feito){'[x]'}else{'[ ]'};$l+="- $m $($p.nome)"};$m=if($f.testeConcluido){'[x]'}else{'[ ]'};$l+="- $m Teste final";[IO.File]::WriteAllLines($PainelPath,[string[]]$l,(New-Object Text.UTF8Encoding($false)))}
function Agora{$e=Ler-Estado;$f=Atual $e;$p=@($f.passos)|?{-not $_.feito}|select -First 1;Write-Host "";Write-Host "MEUROADMAP" -ForegroundColor Cyan;Write-Host "Fase $($f.id.ToString('00')) - $($f.nome)";Write-Host "Progresso: $(Pct $f)%";Write-Host "";if($p){Write-Host "AGORA: $($p.nome)" -ForegroundColor Green;Write-Host "Guia: $($f.diretorio)\README.md";Write-Host "Depois: concluir"}elseif(!$f.testeConcluido){Write-Host "AGORA: TESTE FINAL" -ForegroundColor Yellow;Write-Host "Execute: teste";Write-Host "Depois: aprovar"}else{Write-Host "Fase concluida." -ForegroundColor Green};Write-Host ""}
function Concluir{$e=Ler-Estado;$f=Atual $e;$p=@($f.passos)|?{-not $_.feito}|select -First 1;if(!$p){Write-Host "As 4 etapas ja foram concluidas. Execute 'teste'.";return};$p.feito=$true;Salvar $e;Painel $e;Write-Host "Etapa concluida: $($p.nome)" -ForegroundColor Green;Agora}
function Teste{$e=Ler-Estado;$f=Atual $e;if(@($f.passos)|?{-not $_.feito}){Write-Host "Conclua as 4 etapas antes do teste." -ForegroundColor Yellow;Agora;return};Write-Host "";Write-Host "TESTE FINAL - FASE $($f.id.ToString('00'))" -ForegroundColor Cyan;for($i=0;$i -lt @($f.teste).Count;$i++){Write-Host "$($i+1). $($f.teste[$i])"};Write-Host "";Write-Host "Responda sem consultar. Se passou, execute: aprovar" -ForegroundColor Yellow}
function Aprovar{$e=Ler-Estado;$f=Atual $e;if(@($f.passos)|?{-not $_.feito}){Write-Host "Ainda existem etapas pendentes." -ForegroundColor Yellow;Agora;return};$f.testeConcluido=$true;$f.status="CONCLUIDA";$n=Prox $e $f;if($n){$e.faseAtual=[int]$n.id;$n.status="EM_ANDAMENTO";Salvar $e;Painel $e;Write-Host "FASE CONCLUIDA - PROXIMA FASE LIBERADA." -ForegroundColor Green}else{Salvar $e;Painel $e;Write-Host "ROADMAP CONCLUIDO." -ForegroundColor Green};Agora}
function Status{$e=Ler-Estado;$f=Atual $e;Painel $e;Write-Host "";Write-Host "STATUS" -ForegroundColor Cyan;Write-Host "Fase atual : $($f.id.ToString('00')) - $($f.nome)";Write-Host "Progresso  : $(Pct $f)%";foreach($p in @($f.passos)){Write-Host "$(if($p.feito){'[x]'}else{'[ ]'}) $($p.nome)"};Write-Host "$(if($f.testeConcluido){'[x]'}else{'[ ]'}) Teste final";Write-Host ""}
function Ajuda{Write-Host "MEUROADMAP - comandos" -ForegroundColor Cyan;Write-Host "agora     proximo passo";Write-Host "estudar   alias de agora";Write-Host "concluir  marca a etapa atual";Write-Host "teste     mostra as perguntas";Write-Host "aprovar   libera a proxima fase";Write-Host "status    mostra o progresso";Write-Host "verificar audita a estrutura"}
switch($Comando.ToLower()){'agora'{Agora}'estudar'{Agora}'proximo'{Agora}'concluir'{Concluir}'teste'{Teste}'validar'{Teste}'aprovar'{Aprovar}'status'{Status}'verificar'{if(Test-Path $VerificarPath){& powershell -NoProfile -ExecutionPolicy Bypass -File $VerificarPath}else{Write-Host "Verificador nao encontrado."}}'ajuda'{Ajuda}default{Ajuda}}
